/*!
 * Knockout JavaScript library v3.1.0
 * (c) Steven Sanderson - http://knockoutjs.com/
 * License: MIT (http://www.opensource.org/licenses/mit-license.php)
 */

(function() {(function(p){var z=this||(0,eval)("this"),x=z.document,L=z.navigator,t=z.jQuery,C=z.JSON;(function(p){"function"===typeof require&&"object"===typeof exports&&"object"===typeof module?p(module.exports||exports,require):"function"===typeof define&&define.amd?define(["exports","require"],p):p(z.ko={})})(function(M,N){function H(a,d){return null===a||typeof a in P?a===d:!1}function Q(a,d){var c;return function(){c||(c=setTimeout(function(){c=p;a()},d))}}function R(a,d){var c;return function(){clearTimeout(c);
c=setTimeout(a,d)}}function I(b,d,c,e){a.d[b]={init:function(b,h,g,k,l){var n,q;a.L(function(){var g=a.a.c(h()),k=!c!==!g,s=!q;if(s||d||k!==n)s&&a.ga.ja()&&(q=a.a.fa(a.e.childNodes(b),!0)),k?(s||a.e.S(b,a.a.fa(q)),a.Ca(e?e(l,g):l,b)):a.e.ha(b),n=k},null,{t:b});return{controlsDescendantBindings:!0}}};a.h.ea[b]=!1;a.e.P[b]=!0}var a="undefined"!==typeof M?M:{};a.b=function(b,d){for(var c=b.split("."),e=a,f=0;f<c.length-1;f++)e=e[c[f]];e[c[c.length-1]]=d};a.v=function(a,d,c){a[d]=c};a.version="3.1.0";
a.b("version",a.version);a.a=function(){function b(a,b){for(var c in a)a.hasOwnProperty(c)&&b(c,a[c])}function d(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a}function c(a,b){a.__proto__=b;return a}var e={__proto__:[]}instanceof Array,f={},h={};f[L&&/Firefox\/2/i.test(L.userAgent)?"KeyboardEvent":"UIEvents"]=["keyup","keydown","keypress"];f.MouseEvents="click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave".split(" ");b(f,function(a,b){if(b.length)for(var c=
0,d=b.length;c<d;c++)h[b[c]]=a});var g={propertychange:!0},k=x&&function(){for(var a=3,b=x.createElement("div"),c=b.getElementsByTagName("i");b.innerHTML="\x3c!--[if gt IE "+ ++a+"]><i></i><![endif]--\x3e",c[0];);return 4<a?a:p}();return{sb:["authenticity_token",/^__RequestVerificationToken(_.*)?$/],s:function(a,b){for(var c=0,d=a.length;c<d;c++)b(a[c],c)},m:function(a,b){if("function"==typeof Array.prototype.indexOf)return Array.prototype.indexOf.call(a,b);for(var c=0,d=a.length;c<d;c++)if(a[c]===
b)return c;return-1},mb:function(a,b,c){for(var d=0,g=a.length;d<g;d++)if(b.call(c,a[d],d))return a[d];return null},qa:function(l,b){var c=a.a.m(l,b);0<c?l.splice(c,1):0===c&&l.shift()},nb:function(l){l=l||[];for(var b=[],c=0,d=l.length;c<d;c++)0>a.a.m(b,l[c])&&b.push(l[c]);return b},Da:function(a,b){a=a||[];for(var c=[],d=0,g=a.length;d<g;d++)c.push(b(a[d],d));return c},pa:function(a,b){a=a||[];for(var c=[],d=0,g=a.length;d<g;d++)b(a[d],d)&&c.push(a[d]);return c},da:function(a,b){if(b instanceof
Array)a.push.apply(a,b);else for(var c=0,d=b.length;c<d;c++)a.push(b[c]);return a},ba:function(b,c,d){var g=a.a.m(a.a.Wa(b),c);0>g?d&&b.push(c):d||b.splice(g,1)},ra:e,extend:d,va:c,wa:e?c:d,D:b,la:function(a,b){if(!a)return a;var c={},d;for(d in a)a.hasOwnProperty(d)&&(c[d]=b(a[d],d,a));return c},Ka:function(b){for(;b.firstChild;)a.removeNode(b.firstChild)},lc:function(b){b=a.a.R(b);for(var c=x.createElement("div"),d=0,g=b.length;d<g;d++)c.appendChild(a.Q(b[d]));return c},fa:function(b,c){for(var d=
0,g=b.length,k=[];d<g;d++){var e=b[d].cloneNode(!0);k.push(c?a.Q(e):e)}return k},S:function(b,c){a.a.Ka(b);if(c)for(var d=0,g=c.length;d<g;d++)b.appendChild(c[d])},Hb:function(b,c){var d=b.nodeType?[b]:b;if(0<d.length){for(var g=d[0],k=g.parentNode,e=0,f=c.length;e<f;e++)k.insertBefore(c[e],g);e=0;for(f=d.length;e<f;e++)a.removeNode(d[e])}},ia:function(a,b){if(a.length){for(b=8===b.nodeType&&b.parentNode||b;a.length&&a[0].parentNode!==b;)a.shift();if(1<a.length){var c=a[0],d=a[a.length-1];for(a.length=
0;c!==d;)if(a.push(c),c=c.nextSibling,!c)return;a.push(d)}}return a},Jb:function(a,b){7>k?a.setAttribute("selected",b):a.selected=b},xa:function(a){return null===a||a===p?"":a.trim?a.trim():a.toString().replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},xc:function(b,c){for(var d=[],g=(b||"").split(c),k=0,e=g.length;k<e;k++){var f=a.a.xa(g[k]);""!==f&&d.push(f)}return d},sc:function(a,b){a=a||"";return b.length>a.length?!1:a.substring(0,b.length)===b},Zb:function(a,b){if(a===b)return!0;if(11===a.nodeType)return!1;
if(b.contains)return b.contains(3===a.nodeType?a.parentNode:a);if(b.compareDocumentPosition)return 16==(b.compareDocumentPosition(a)&16);for(;a&&a!=b;)a=a.parentNode;return!!a},Ja:function(b){return a.a.Zb(b,b.ownerDocument.documentElement)},kb:function(b){return!!a.a.mb(b,a.a.Ja)},A:function(a){return a&&a.tagName&&a.tagName.toLowerCase()},r:function(b,c,d){var e=k&&g[c];if(!e&&t)t(b).bind(c,d);else if(e||"function"!=typeof b.addEventListener)if("undefined"!=typeof b.attachEvent){var f=function(a){d.call(b,
a)},h="on"+c;b.attachEvent(h,f);a.a.u.aa(b,function(){b.detachEvent(h,f)})}else throw Error("Browser doesn't support addEventListener or attachEvent");else b.addEventListener(c,d,!1)},ma:function(b,c){if(!b||!b.nodeType)throw Error("element must be a DOM node when calling triggerEvent");var d;"input"===a.a.A(b)&&b.type&&"click"==c.toLowerCase()?(d=b.type,d="checkbox"==d||"radio"==d):d=!1;if(t&&!d)t(b).trigger(c);else if("function"==typeof x.createEvent)if("function"==typeof b.dispatchEvent)d=x.createEvent(h[c]||
"HTMLEvents"),d.initEvent(c,!0,!0,z,0,0,0,0,0,!1,!1,!1,!1,0,b),b.dispatchEvent(d);else throw Error("The supplied element doesn't support dispatchEvent");else if(d&&b.click)b.click();else if("undefined"!=typeof b.fireEvent)b.fireEvent("on"+c);else throw Error("Browser doesn't support triggering events");},c:function(b){return a.B(b)?b():b},Wa:function(b){return a.B(b)?b.o():b},ya:function(b,c,d){if(c){var g=/\S+/g,k=b.className.match(g)||[];a.a.s(c.match(g),function(b){a.a.ba(k,b,d)});b.className=
k.join(" ")}},ab:function(b,c){var d=a.a.c(c);if(null===d||d===p)d="";var g=a.e.firstChild(b);!g||3!=g.nodeType||a.e.nextSibling(g)?a.e.S(b,[b.ownerDocument.createTextNode(d)]):g.data=d;a.a.bc(b)},Ib:function(a,b){a.name=b;if(7>=k)try{a.mergeAttributes(x.createElement("<input name='"+a.name+"'/>"),!1)}catch(c){}},bc:function(a){9<=k&&(a=1==a.nodeType?a:a.parentNode,a.style&&(a.style.zoom=a.style.zoom))},$b:function(a){if(k){var b=a.style.width;a.style.width=0;a.style.width=b}},pc:function(b,c){b=
a.a.c(b);c=a.a.c(c);for(var d=[],g=b;g<=c;g++)d.push(g);return d},R:function(a){for(var b=[],c=0,d=a.length;c<d;c++)b.push(a[c]);return b},vc:6===k,wc:7===k,ka:k,ub:function(b,c){for(var d=a.a.R(b.getElementsByTagName("input")).concat(a.a.R(b.getElementsByTagName("textarea"))),g="string"==typeof c?function(a){return a.name===c}:function(a){return c.test(a.name)},k=[],e=d.length-1;0<=e;e--)g(d[e])&&k.push(d[e]);return k},mc:function(b){return"string"==typeof b&&(b=a.a.xa(b))?C&&C.parse?C.parse(b):
(new Function("return "+b))():null},bb:function(b,c,d){if(!C||!C.stringify)throw Error("Cannot find JSON.stringify(). Some browsers (e.g., IE < 8) don't support it natively, but you can overcome this by adding a script reference to json2.js, downloadable from http://www.json.org/json2.js");return C.stringify(a.a.c(b),c,d)},nc:function(c,d,g){g=g||{};var k=g.params||{},e=g.includeFields||this.sb,f=c;if("object"==typeof c&&"form"===a.a.A(c))for(var f=c.action,h=e.length-1;0<=h;h--)for(var v=a.a.ub(c,
e[h]),D=v.length-1;0<=D;D--)k[v[D].name]=v[D].value;d=a.a.c(d);var B=x.createElement("form");B.style.display="none";B.action=f;B.method="post";for(var p in d)c=x.createElement("input"),c.name=p,c.value=a.a.bb(a.a.c(d[p])),B.appendChild(c);b(k,function(a,b){var c=x.createElement("input");c.name=a;c.value=b;B.appendChild(c)});x.body.appendChild(B);g.submitter?g.submitter(B):B.submit();setTimeout(function(){B.parentNode.removeChild(B)},0)}}}();a.b("utils",a.a);a.b("utils.arrayForEach",a.a.s);a.b("utils.arrayFirst",
a.a.mb);a.b("utils.arrayFilter",a.a.pa);a.b("utils.arrayGetDistinctValues",a.a.nb);a.b("utils.arrayIndexOf",a.a.m);a.b("utils.arrayMap",a.a.Da);a.b("utils.arrayPushAll",a.a.da);a.b("utils.arrayRemoveItem",a.a.qa);a.b("utils.extend",a.a.extend);a.b("utils.fieldsIncludedWithJsonPost",a.a.sb);a.b("utils.getFormFields",a.a.ub);a.b("utils.peekObservable",a.a.Wa);a.b("utils.postJson",a.a.nc);a.b("utils.parseJson",a.a.mc);a.b("utils.registerEventHandler",a.a.r);a.b("utils.stringifyJson",a.a.bb);a.b("utils.range",
a.a.pc);a.b("utils.toggleDomNodeCssClass",a.a.ya);a.b("utils.triggerEvent",a.a.ma);a.b("utils.unwrapObservable",a.a.c);a.b("utils.objectForEach",a.a.D);a.b("utils.addOrRemoveItem",a.a.ba);a.b("unwrap",a.a.c);Function.prototype.bind||(Function.prototype.bind=function(a){var d=this,c=Array.prototype.slice.call(arguments);a=c.shift();return function(){return d.apply(a,c.concat(Array.prototype.slice.call(arguments)))}});a.a.f=new function(){function a(b,h){var g=b[c];if(!g||"null"===g||!e[g]){if(!h)return p;
g=b[c]="ko"+d++;e[g]={}}return e[g]}var d=0,c="__ko__"+(new Date).getTime(),e={};return{get:function(c,d){var g=a(c,!1);return g===p?p:g[d]},set:function(c,d,g){if(g!==p||a(c,!1)!==p)a(c,!0)[d]=g},clear:function(a){var b=a[c];return b?(delete e[b],a[c]=null,!0):!1},N:function(){return d++ +c}}};a.b("utils.domData",a.a.f);a.b("utils.domData.clear",a.a.f.clear);a.a.u=new function(){function b(b,d){var k=a.a.f.get(b,c);k===p&&d&&(k=[],a.a.f.set(b,c,k));return k}function d(c){var g=b(c,!1);if(g)for(var g=
g.slice(0),k=0;k<g.length;k++)g[k](c);a.a.f.clear(c);a.a.u.cleanExternalData(c);if(f[c.nodeType])for(g=c.firstChild;c=g;)g=c.nextSibling,8===c.nodeType&&d(c)}var c=a.a.f.N(),e={1:!0,8:!0,9:!0},f={1:!0,9:!0};return{aa:function(a,c){if("function"!=typeof c)throw Error("Callback must be a function");b(a,!0).push(c)},Gb:function(d,g){var k=b(d,!1);k&&(a.a.qa(k,g),0==k.length&&a.a.f.set(d,c,p))},Q:function(b){if(e[b.nodeType]&&(d(b),f[b.nodeType])){var c=[];a.a.da(c,b.getElementsByTagName("*"));for(var k=
0,l=c.length;k<l;k++)d(c[k])}return b},removeNode:function(b){a.Q(b);b.parentNode&&b.parentNode.removeChild(b)},cleanExternalData:function(a){t&&"function"==typeof t.cleanData&&t.cleanData([a])}}};a.Q=a.a.u.Q;a.removeNode=a.a.u.removeNode;a.b("cleanNode",a.Q);a.b("removeNode",a.removeNode);a.b("utils.domNodeDisposal",a.a.u);a.b("utils.domNodeDisposal.addDisposeCallback",a.a.u.aa);a.b("utils.domNodeDisposal.removeDisposeCallback",a.a.u.Gb);(function(){a.a.ta=function(b){var d;if(t)if(t.parseHTML)d=
t.parseHTML(b)||[];else{if((d=t.clean([b]))&&d[0]){for(b=d[0];b.parentNode&&11!==b.parentNode.nodeType;)b=b.parentNode;b.parentNode&&b.parentNode.removeChild(b)}}else{var c=a.a.xa(b).toLowerCase();d=x.createElement("div");c=c.match(/^<(thead|tbody|tfoot)/)&&[1,"<table>","</table>"]||!c.indexOf("<tr")&&[2,"<table><tbody>","</tbody></table>"]||(!c.indexOf("<td")||!c.indexOf("<th"))&&[3,"<table><tbody><tr>","</tr></tbody></table>"]||[0,"",""];b="ignored<div>"+c[1]+b+c[2]+"</div>";for("function"==typeof z.innerShiv?
d.appendChild(z.innerShiv(b)):d.innerHTML=b;c[0]--;)d=d.lastChild;d=a.a.R(d.lastChild.childNodes)}return d};a.a.Za=function(b,d){a.a.Ka(b);d=a.a.c(d);if(null!==d&&d!==p)if("string"!=typeof d&&(d=d.toString()),t)t(b).html(d);else for(var c=a.a.ta(d),e=0;e<c.length;e++)b.appendChild(c[e])}})();a.b("utils.parseHtmlFragment",a.a.ta);a.b("utils.setHtml",a.a.Za);a.C=function(){function b(c,d){if(c)if(8==c.nodeType){var f=a.C.Db(c.nodeValue);null!=f&&d.push({Yb:c,jc:f})}else if(1==c.nodeType)for(var f=0,
h=c.childNodes,g=h.length;f<g;f++)b(h[f],d)}var d={};return{Ta:function(a){if("function"!=typeof a)throw Error("You can only pass a function to ko.memoization.memoize()");var b=(4294967296*(1+Math.random())|0).toString(16).substring(1)+(4294967296*(1+Math.random())|0).toString(16).substring(1);d[b]=a;return"\x3c!--[ko_memo:"+b+"]--\x3e"},Nb:function(a,b){var f=d[a];if(f===p)throw Error("Couldn't find any memo with ID "+a+". Perhaps it's already been unmemoized.");try{return f.apply(null,b||[]),!0}finally{delete d[a]}},
Ob:function(c,d){var f=[];b(c,f);for(var h=0,g=f.length;h<g;h++){var k=f[h].Yb,l=[k];d&&a.a.da(l,d);a.C.Nb(f[h].jc,l);k.nodeValue="";k.parentNode&&k.parentNode.removeChild(k)}},Db:function(a){return(a=a.match(/^\[ko_memo\:(.*?)\]$/))?a[1]:null}}}();a.b("memoization",a.C);a.b("memoization.memoize",a.C.Ta);a.b("memoization.unmemoize",a.C.Nb);a.b("memoization.parseMemoText",a.C.Db);a.b("memoization.unmemoizeDomNodeAndDescendants",a.C.Ob);a.La={throttle:function(b,d){b.throttleEvaluation=d;var c=null;
return a.i({read:b,write:function(a){clearTimeout(c);c=setTimeout(function(){b(a)},d)}})},rateLimit:function(a,d){var c,e,f;"number"==typeof d?c=d:(c=d.timeout,e=d.method);f="notifyWhenChangesStop"==e?R:Q;a.Sa(function(a){return f(a,c)})},notify:function(a,d){a.equalityComparer="always"==d?null:H}};var P={undefined:1,"boolean":1,number:1,string:1};a.b("extenders",a.La);a.Lb=function(b,d,c){this.target=b;this.Ea=d;this.Xb=c;this.yb=!1;a.v(this,"dispose",this.I)};a.Lb.prototype.I=function(){this.yb=
!0;this.Xb()};a.O=function(){a.a.wa(this,a.O.fn);this.J={}};var G="change",A={T:function(b,d,c){var e=this;c=c||G;var f=new a.Lb(e,d?b.bind(d):b,function(){a.a.qa(e.J[c],f)});e.o&&e.o();e.J[c]||(e.J[c]=[]);e.J[c].push(f);return f},notifySubscribers:function(b,d){d=d||G;if(this.wb(d))try{a.l.ob();for(var c=this.J[d].slice(0),e=0,f;f=c[e];++e)f.yb||f.Ea(b)}finally{a.l.end()}},Sa:function(b){var d=this,c=a.B(d),e,f,h;d.na||(d.na=d.notifySubscribers,d.notifySubscribers=function(a,b){b&&b!==G?"beforeChange"===
b?d.hb(a):d.na(a,b):d.ib(a)});var g=b(function(){c&&h===d&&(h=d());e=!1;d.Pa(f,h)&&d.na(f=h)});d.ib=function(a){e=!0;h=a;g()};d.hb=function(a){e||(f=a,d.na(a,"beforeChange"))}},wb:function(a){return this.J[a]&&this.J[a].length},cc:function(){var b=0;a.a.D(this.J,function(a,c){b+=c.length});return b},Pa:function(a,d){return!this.equalityComparer||!this.equalityComparer(a,d)},extend:function(b){var d=this;b&&a.a.D(b,function(b,e){var f=a.La[b];"function"==typeof f&&(d=f(d,e)||d)});return d}};a.v(A,
"subscribe",A.T);a.v(A,"extend",A.extend);a.v(A,"getSubscriptionsCount",A.cc);a.a.ra&&a.a.va(A,Function.prototype);a.O.fn=A;a.zb=function(a){return null!=a&&"function"==typeof a.T&&"function"==typeof a.notifySubscribers};a.b("subscribable",a.O);a.b("isSubscribable",a.zb);a.ga=a.l=function(){function b(a){c.push(e);e=a}function d(){e=c.pop()}var c=[],e,f=0;return{ob:b,end:d,Fb:function(b){if(e){if(!a.zb(b))throw Error("Only subscribable things can act as dependencies");e.Ea(b,b.Rb||(b.Rb=++f))}},w:function(a,
c,k){try{return b(),a.apply(c,k||[])}finally{d()}},ja:function(){if(e)return e.L.ja()},sa:function(){if(e)return e.sa}}}();a.b("computedContext",a.ga);a.b("computedContext.getDependenciesCount",a.ga.ja);a.b("computedContext.isInitial",a.ga.sa);a.n=function(b){function d(){if(0<arguments.length)return d.Pa(c,arguments[0])&&(d.V(),c=arguments[0],d.U()),this;a.l.Fb(d);return c}var c=b;a.O.call(d);a.a.wa(d,a.n.fn);d.o=function(){return c};d.U=function(){d.notifySubscribers(c)};d.V=function(){d.notifySubscribers(c,
"beforeChange")};a.v(d,"peek",d.o);a.v(d,"valueHasMutated",d.U);a.v(d,"valueWillMutate",d.V);return d};a.n.fn={equalityComparer:H};var E=a.n.oc="__ko_proto__";a.n.fn[E]=a.n;a.a.ra&&a.a.va(a.n.fn,a.O.fn);a.Ma=function(b,d){return null===b||b===p||b[E]===p?!1:b[E]===d?!0:a.Ma(b[E],d)};a.B=function(b){return a.Ma(b,a.n)};a.Ab=function(b){return"function"==typeof b&&b[E]===a.n||"function"==typeof b&&b[E]===a.i&&b.ec?!0:!1};a.b("observable",a.n);a.b("isObservable",a.B);a.b("isWriteableObservable",a.Ab);
a.Y=function(b){b=b||[];if("object"!=typeof b||!("length"in b))throw Error("The argument passed when initializing an observable array must be an array, or null, or undefined.");b=a.n(b);a.a.wa(b,a.Y.fn);return b.extend({trackArrayChanges:!0})};a.Y.fn={remove:function(b){for(var d=this.o(),c=[],e="function"!=typeof b||a.B(b)?function(a){return a===b}:b,f=0;f<d.length;f++){var h=d[f];e(h)&&(0===c.length&&this.V(),c.push(h),d.splice(f,1),f--)}c.length&&this.U();return c},removeAll:function(b){if(b===
p){var d=this.o(),c=d.slice(0);this.V();d.splice(0,d.length);this.U();return c}return b?this.remove(function(c){return 0<=a.a.m(b,c)}):[]},destroy:function(b){var d=this.o(),c="function"!=typeof b||a.B(b)?function(a){return a===b}:b;this.V();for(var e=d.length-1;0<=e;e--)c(d[e])&&(d[e]._destroy=!0);this.U()},destroyAll:function(b){return b===p?this.destroy(function(){return!0}):b?this.destroy(function(d){return 0<=a.a.m(b,d)}):[]},indexOf:function(b){var d=this();return a.a.m(d,b)},replace:function(a,
d){var c=this.indexOf(a);0<=c&&(this.V(),this.o()[c]=d,this.U())}};a.a.s("pop push reverse shift sort splice unshift".split(" "),function(b){a.Y.fn[b]=function(){var a=this.o();this.V();this.pb(a,b,arguments);a=a[b].apply(a,arguments);this.U();return a}});a.a.s(["slice"],function(b){a.Y.fn[b]=function(){var a=this();return a[b].apply(a,arguments)}});a.a.ra&&a.a.va(a.Y.fn,a.n.fn);a.b("observableArray",a.Y);var J="arrayChange";a.La.trackArrayChanges=function(b){function d(){if(!c){c=!0;var d=b.notifySubscribers;
b.notifySubscribers=function(a,b){b&&b!==G||++f;return d.apply(this,arguments)};var k=[].concat(b.o()||[]);e=null;b.T(function(c){c=[].concat(c||[]);if(b.wb(J)){var d;if(!e||1<f)e=a.a.Fa(k,c,{sparse:!0});d=e;d.length&&b.notifySubscribers(d,J)}k=c;e=null;f=0})}}if(!b.pb){var c=!1,e=null,f=0,h=b.T;b.T=b.subscribe=function(a,b,c){c===J&&d();return h.apply(this,arguments)};b.pb=function(b,d,l){function n(a,b,c){return h[h.length]={status:a,value:b,index:c}}if(c&&!f){var h=[],m=b.length,r=l.length,s=0;
switch(d){case "push":s=m;case "unshift":for(d=0;d<r;d++)n("added",l[d],s+d);break;case "pop":s=m-1;case "shift":m&&n("deleted",b[s],s);break;case "splice":d=Math.min(Math.max(0,0>l[0]?m+l[0]:l[0]),m);for(var m=1===r?m:Math.min(d+(l[1]||0),m),r=d+r-2,s=Math.max(m,r),u=[],v=[],D=2;d<s;++d,++D)d<m&&v.push(n("deleted",b[d],d)),d<r&&u.push(n("added",l[D],d));a.a.tb(v,u);break;default:return}e=h}}}};a.L=a.i=function(b,d,c){function e(){r=!0;a.a.D(w,function(a,b){b.I()});w={};y=0;n=!1}function f(){var a=
g.throttleEvaluation;a&&0<=a?(clearTimeout(t),t=setTimeout(h,a)):g.Aa?g.Aa():h()}function h(){if(!q&&!r){if(p&&p()){if(!m){F();return}}else m=!1;q=!0;try{var b=w,c=y;a.l.ob({Ea:function(a,d){r||(c&&b[d]?(w[d]=b[d],++y,delete b[d],--c):w[d]||(w[d]=a.T(f),++y))},L:g,sa:!y});w={};y=0;try{var k=d?s.call(d):s()}finally{a.l.end(),c&&a.a.D(b,function(a,b){b.I()}),n=!1}g.Pa(l,k)&&(g.notifySubscribers(l,"beforeChange"),l=k,g.Aa&&!g.throttleEvaluation||g.notifySubscribers(l))}finally{q=!1}y||F()}}function g(){if(0<
arguments.length){if("function"===typeof u)u.apply(d,arguments);else throw Error("Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.");return this}n&&h();a.l.Fb(g);return l}function k(){return n||0<y}var l,n=!0,q=!1,m=!1,r=!1,s=b;s&&"object"==typeof s?(c=s,s=c.read):(c=c||{},s||(s=c.read));if("function"!=typeof s)throw Error("Pass a function that returns the value of the ko.computed");var u=c.write,v=c.disposeWhenNodeIsRemoved||
c.t||null,D=c.disposeWhen||c.Ia,p=D,F=e,w={},y=0,t=null;d||(d=c.owner);a.O.call(g);a.a.wa(g,a.i.fn);g.o=function(){n&&!y&&h();return l};g.ja=function(){return y};g.ec="function"===typeof c.write;g.I=function(){F()};g.W=k;var x=g.Sa;g.Sa=function(a){x.call(g,a);g.Aa=function(){g.hb(l);n=!0;g.ib(g)}};a.v(g,"peek",g.o);a.v(g,"dispose",g.I);a.v(g,"isActive",g.W);a.v(g,"getDependenciesCount",g.ja);v&&(m=!0,v.nodeType&&(p=function(){return!a.a.Ja(v)||D&&D()}));!0!==c.deferEvaluation&&h();v&&k()&&v.nodeType&&
(F=function(){a.a.u.Gb(v,F);e()},a.a.u.aa(v,F));return g};a.gc=function(b){return a.Ma(b,a.i)};A=a.n.oc;a.i[A]=a.n;a.i.fn={equalityComparer:H};a.i.fn[A]=a.i;a.a.ra&&a.a.va(a.i.fn,a.O.fn);a.b("dependentObservable",a.i);a.b("computed",a.i);a.b("isComputed",a.gc);(function(){function b(a,f,h){h=h||new c;a=f(a);if("object"!=typeof a||null===a||a===p||a instanceof Date||a instanceof String||a instanceof Number||a instanceof Boolean)return a;var g=a instanceof Array?[]:{};h.save(a,g);d(a,function(c){var d=
f(a[c]);switch(typeof d){case "boolean":case "number":case "string":case "function":g[c]=d;break;case "object":case "undefined":var n=h.get(d);g[c]=n!==p?n:b(d,f,h)}});return g}function d(a,b){if(a instanceof Array){for(var c=0;c<a.length;c++)b(c);"function"==typeof a.toJSON&&b("toJSON")}else for(c in a)b(c)}function c(){this.keys=[];this.fb=[]}a.Mb=function(c){if(0==arguments.length)throw Error("When calling ko.toJS, pass the object you want to convert.");return b(c,function(b){for(var c=0;a.B(b)&&
10>c;c++)b=b();return b})};a.toJSON=function(b,c,d){b=a.Mb(b);return a.a.bb(b,c,d)};c.prototype={save:function(b,c){var d=a.a.m(this.keys,b);0<=d?this.fb[d]=c:(this.keys.push(b),this.fb.push(c))},get:function(b){b=a.a.m(this.keys,b);return 0<=b?this.fb[b]:p}}})();a.b("toJS",a.Mb);a.b("toJSON",a.toJSON);(function(){a.j={q:function(b){switch(a.a.A(b)){case "option":return!0===b.__ko__hasDomDataOptionValue__?a.a.f.get(b,a.d.options.Ua):7>=a.a.ka?b.getAttributeNode("value")&&b.getAttributeNode("value").specified?
b.value:b.text:b.value;case "select":return 0<=b.selectedIndex?a.j.q(b.options[b.selectedIndex]):p;default:return b.value}},$:function(b,d,c){switch(a.a.A(b)){case "option":switch(typeof d){case "string":a.a.f.set(b,a.d.options.Ua,p);"__ko__hasDomDataOptionValue__"in b&&delete b.__ko__hasDomDataOptionValue__;b.value=d;break;default:a.a.f.set(b,a.d.options.Ua,d),b.__ko__hasDomDataOptionValue__=!0,b.value="number"===typeof d?d:""}break;case "select":if(""===d||null===d)d=p;for(var e=-1,f=0,h=b.options.length,
g;f<h;++f)if(g=a.j.q(b.options[f]),g==d||""==g&&d===p){e=f;break}if(c||0<=e||d===p&&1<b.size)b.selectedIndex=e;break;default:if(null===d||d===p)d="";b.value=d}}}})();a.b("selectExtensions",a.j);a.b("selectExtensions.readValue",a.j.q);a.b("selectExtensions.writeValue",a.j.$);a.h=function(){function b(b){b=a.a.xa(b);123===b.charCodeAt(0)&&(b=b.slice(1,-1));var c=[],d=b.match(e),g,m,r=0;if(d){d.push(",");for(var s=0,u;u=d[s];++s){var v=u.charCodeAt(0);if(44===v){if(0>=r){g&&c.push(m?{key:g,value:m.join("")}:
{unknown:g});g=m=r=0;continue}}else if(58===v){if(!m)continue}else if(47===v&&s&&1<u.length)(v=d[s-1].match(f))&&!h[v[0]]&&(b=b.substr(b.indexOf(u)+1),d=b.match(e),d.push(","),s=-1,u="/");else if(40===v||123===v||91===v)++r;else if(41===v||125===v||93===v)--r;else if(!g&&!m){g=34===v||39===v?u.slice(1,-1):u;continue}m?m.push(u):m=[u]}}return c}var d=["true","false","null","undefined"],c=/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i,e=RegExp("\"(?:[^\"\\\\]|\\\\.)*\"|'(?:[^'\\\\]|\\\\.)*'|/(?:[^/\\\\]|\\\\.)*/w*|[^\\s:,/][^,\"'{}()/:[\\]]*[^\\s,\"'{}()/:[\\]]|[^\\s]",
"g"),f=/[\])"'A-Za-z0-9_$]+$/,h={"in":1,"return":1,"typeof":1},g={};return{ea:[],Z:g,Va:b,ua:function(k,l){function e(b,k){var l;if(!s){var u=a.getBindingHandler(b);if(u&&u.preprocess&&!(k=u.preprocess(k,b,e)))return;if(u=g[b])l=k,0<=a.a.m(d,l)?l=!1:(u=l.match(c),l=null===u?!1:u[1]?"Object("+u[1]+")"+u[2]:l),u=l;u&&h.push("'"+b+"':function(_z){"+l+"=_z}")}r&&(k="function(){return "+k+" }");f.push("'"+b+"':"+k)}l=l||{};var f=[],h=[],r=l.valueAccessors,s=l.bindingParams,u="string"===typeof k?b(k):k;
a.a.s(u,function(a){e(a.key||a.unknown,a.value)});h.length&&e("_ko_property_writers","{"+h.join(",")+" }");return f.join(",")},ic:function(a,b){for(var c=0;c<a.length;c++)if(a[c].key==b)return!0;return!1},za:function(b,c,d,g,e){if(b&&a.B(b))!a.Ab(b)||e&&b.o()===g||b(g);else if((b=c.get("_ko_property_writers"))&&b[d])b[d](g)}}}();a.b("expressionRewriting",a.h);a.b("expressionRewriting.bindingRewriteValidators",a.h.ea);a.b("expressionRewriting.parseObjectLiteral",a.h.Va);a.b("expressionRewriting.preProcessBindings",
a.h.ua);a.b("expressionRewriting._twoWayBindings",a.h.Z);a.b("jsonExpressionRewriting",a.h);a.b("jsonExpressionRewriting.insertPropertyAccessorsIntoJson",a.h.ua);(function(){function b(a){return 8==a.nodeType&&h.test(f?a.text:a.nodeValue)}function d(a){return 8==a.nodeType&&g.test(f?a.text:a.nodeValue)}function c(a,c){for(var g=a,k=1,e=[];g=g.nextSibling;){if(d(g)&&(k--,0===k))return e;e.push(g);b(g)&&k++}if(!c)throw Error("Cannot find closing comment tag to match: "+a.nodeValue);return null}function e(a,
b){var d=c(a,b);return d?0<d.length?d[d.length-1].nextSibling:a.nextSibling:null}var f=x&&"\x3c!--test--\x3e"===x.createComment("test").text,h=f?/^\x3c!--\s*ko(?:\s+([\s\S]+))?\s*--\x3e$/:/^\s*ko(?:\s+([\s\S]+))?\s*$/,g=f?/^\x3c!--\s*\/ko\s*--\x3e$/:/^\s*\/ko\s*$/,k={ul:!0,ol:!0};a.e={P:{},childNodes:function(a){return b(a)?c(a):a.childNodes},ha:function(c){if(b(c)){c=a.e.childNodes(c);for(var d=0,g=c.length;d<g;d++)a.removeNode(c[d])}else a.a.Ka(c)},S:function(c,d){if(b(c)){a.e.ha(c);for(var g=c.nextSibling,
k=0,e=d.length;k<e;k++)g.parentNode.insertBefore(d[k],g)}else a.a.S(c,d)},Eb:function(a,c){b(a)?a.parentNode.insertBefore(c,a.nextSibling):a.firstChild?a.insertBefore(c,a.firstChild):a.appendChild(c)},xb:function(c,d,g){g?b(c)?c.parentNode.insertBefore(d,g.nextSibling):g.nextSibling?c.insertBefore(d,g.nextSibling):c.appendChild(d):a.e.Eb(c,d)},firstChild:function(a){return b(a)?!a.nextSibling||d(a.nextSibling)?null:a.nextSibling:a.firstChild},nextSibling:function(a){b(a)&&(a=e(a));return a.nextSibling&&
d(a.nextSibling)?null:a.nextSibling},dc:b,uc:function(a){return(a=(f?a.text:a.nodeValue).match(h))?a[1]:null},Cb:function(c){if(k[a.a.A(c)]){var g=c.firstChild;if(g){do if(1===g.nodeType){var f;f=g.firstChild;var h=null;if(f){do if(h)h.push(f);else if(b(f)){var r=e(f,!0);r?f=r:h=[f]}else d(f)&&(h=[f]);while(f=f.nextSibling)}if(f=h)for(h=g.nextSibling,r=0;r<f.length;r++)h?c.insertBefore(f[r],h):c.appendChild(f[r])}while(g=g.nextSibling)}}}}})();a.b("virtualElements",a.e);a.b("virtualElements.allowedBindings",
a.e.P);a.b("virtualElements.emptyNode",a.e.ha);a.b("virtualElements.insertAfter",a.e.xb);a.b("virtualElements.prepend",a.e.Eb);a.b("virtualElements.setDomNodeChildren",a.e.S);(function(){a.H=function(){this.Ub={}};a.a.extend(a.H.prototype,{nodeHasBindings:function(b){switch(b.nodeType){case 1:return null!=b.getAttribute("data-bind")||a.g.getComponentNameForNode(b);case 8:return a.e.dc(b);default:return!1}},getBindings:function(b,d){var c=this.getBindingsString(b,d),c=c?this.parseBindingsString(c,
d,b):null;return a.g.jb(c,b,d,!1)},getBindingAccessors:function(b,d){var c=this.getBindingsString(b,d),c=c?this.parseBindingsString(c,d,b,{valueAccessors:!0}):null;return a.g.jb(c,b,d,!0)},getBindingsString:function(b){switch(b.nodeType){case 1:return b.getAttribute("data-bind");case 8:return a.e.uc(b);default:return null}},parseBindingsString:function(b,d,c,e){try{var f=this.Ub,h=b+(e&&e.valueAccessors||""),g;if(!(g=f[h])){var k,l="with($context){with($data||{}){return{"+a.h.ua(b,e)+"}}}";k=new Function("$context",
"$element",l);g=f[h]=k}return g(d,c)}catch(n){throw n.message="Unable to parse bindings.\nBindings value: "+b+"\nMessage: "+n.message,n;}}});a.H.instance=new a.H})();a.b("bindingProvider",a.H);(function(){function b(a){return function(){return a}}function d(a){return a()}function c(b){return a.a.la(a.l.w(b),function(a,c){return function(){return b()[c]}})}function e(a,b){return c(this.getBindings.bind(this,a,b))}function f(b,c,d){var g,k=a.e.firstChild(c),e=a.H.instance,f=e.preprocessNode;if(f){for(;g=
k;)k=a.e.nextSibling(g),f.call(e,g);k=a.e.firstChild(c)}for(;g=k;)k=a.e.nextSibling(g),h(b,g,d)}function h(b,c,d){var g=!0,e=1===c.nodeType;e&&a.e.Cb(c);if(e&&d||a.H.instance.nodeHasBindings(c))g=k(c,null,b,d).shouldBindDescendants;g&&!n[a.a.A(c)]&&f(b,c,!e)}function g(b){var c=[],d={},g=[];a.a.D(b,function B(k){if(!d[k]){var e=a.getBindingHandler(k);e&&(e.after&&(g.push(k),a.a.s(e.after,function(c){if(b[c]){if(-1!==a.a.m(g,c))throw Error("Cannot combine the following bindings, because they have a cyclic dependency: "+
g.join(", "));B(c)}}),g.length--),c.push({key:k,vb:e}));d[k]=!0}});return c}function k(b,c,k,f){var l=a.a.f.get(b,q);if(!c){if(l)throw Error("You cannot apply bindings multiple times to the same element.");a.a.f.set(b,q,!0)}!l&&f&&a.Kb(b,k);var h;if(c&&"function"!==typeof c)h=c;else{var n=a.H.instance,m=n.getBindingAccessors||e,y=a.i(function(){(h=c?c(k,b):m.call(n,b,k))&&k.G&&k.G();return h},null,{t:b});h&&y.W()||(y=null)}var t;if(h){var x=y?function(a){return function(){return d(y()[a])}}:function(a){return h[a]},
z=function(){return a.a.la(y?y():h,d)};z.get=function(a){return h[a]&&d(x(a))};z.has=function(a){return a in h};f=g(h);a.a.s(f,function(c){var d=c.vb.init,g=c.vb.update,e=c.key;if(8===b.nodeType&&!a.e.P[e])throw Error("The binding '"+e+"' cannot be used with virtual elements");try{"function"==typeof d&&a.l.w(function(){var a=d(b,x(e),z,k.$data,k);if(a&&a.controlsDescendantBindings){if(t!==p)throw Error("Multiple bindings ("+t+" and "+e+") are trying to control descendant bindings of the same element. You cannot use these bindings together on the same element.");
t=e}}),"function"==typeof g&&a.i(function(){g(b,x(e),z,k.$data,k)},null,{t:b})}catch(f){throw f.message='Unable to process binding "'+e+": "+h[e]+'"\nMessage: '+f.message,f;}})}return{shouldBindDescendants:t===p}}function l(b){return b&&b instanceof a.K?b:new a.K(b)}a.d={};var n={script:!0};a.getBindingHandler=function(b){return a.d[b]};a.K=function(b,c,d,g){var k=this,e="function"==typeof b&&!a.B(b),f,l=a.i(function(){var f=e?b():b,h=a.a.c(f);c?(c.G&&c.G(),a.a.extend(k,c),l&&(k.G=l)):(k.$parents=
[],k.$root=h,k.ko=a);k.$rawData=f;k.$data=h;d&&(k[d]=h);g&&g(k,c,h);return k.$data},null,{Ia:function(){return f&&!a.a.kb(f)},t:!0});l.W()&&(k.G=l,l.equalityComparer=null,f=[],l.Pb=function(b){f.push(b);a.a.u.aa(b,function(b){a.a.qa(f,b);f.length||(l.I(),k.G=l=p)})})};a.K.prototype.createChildContext=function(b,c,d){return new a.K(b,this,c,function(a,b){a.$parentContext=b;a.$parent=b.$data;a.$parents=(b.$parents||[]).slice(0);a.$parents.unshift(a.$parent);d&&d(a)})};a.K.prototype.extend=function(b){return new a.K(this.G||
this.$data,this,null,function(c,d){c.$rawData=d.$rawData;a.a.extend(c,"function"==typeof b?b():b)})};var q=a.a.f.N(),m=a.a.f.N();a.Kb=function(b,c){if(2==arguments.length)a.a.f.set(b,m,c),c.G&&c.G.Pb(b);else return a.a.f.get(b,m)};a.Ba=function(b,c,d){1===b.nodeType&&a.e.Cb(b);return k(b,c,l(d),!0)};a.Sb=function(d,g,k){k=l(k);return a.Ba(d,"function"===typeof g?c(g.bind(null,k,d)):a.a.la(g,b),k)};a.Ca=function(a,b){1!==b.nodeType&&8!==b.nodeType||f(l(a),b,!0)};a.lb=function(a,b){!t&&z.jQuery&&(t=
z.jQuery);if(b&&1!==b.nodeType&&8!==b.nodeType)throw Error("ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node");b=b||z.document.body;h(l(a),b,!0)};a.Ha=function(b){switch(b.nodeType){case 1:case 8:var c=a.Kb(b);if(c)return c;if(b.parentNode)return a.Ha(b.parentNode)}return p};a.Wb=function(b){return(b=a.Ha(b))?b.$data:p};a.b("bindingHandlers",a.d);a.b("applyBindings",a.lb);a.b("applyBindingsToDescendants",a.Ca);a.b("applyBindingAccessorsToNode",a.Ba);
a.b("applyBindingsToNode",a.Sb);a.b("contextFor",a.Ha);a.b("dataFor",a.Wb)})();(function(b){function d(d,k){var e=f.hasOwnProperty(d)?f[d]:b,n;e||(e=f[d]=new a.O,c(d,function(a){h[d]=a;delete f[d];n?e.notifySubscribers(a):setTimeout(function(){e.notifySubscribers(a)},0)}),n=!0);e.T(k)}function c(a,b){e("getConfig",[a],function(c){c?e("loadComponent",[a,c],function(a){b(a)}):b(null)})}function e(c,d,f,h){h||(h=a.g.loaders.slice(0));var q=h.shift();if(q){var m=q[c];if(m){var r=!1;if(m.apply(q,d.concat(function(a){r?
f(null):null!==a?f(a):e(c,d,f,h)}))!==b&&(r=!0,!q.suppressLoaderExceptions))throw Error("Component loaders must supply values by invoking the callback, not by returning values synchronously.");}else e(c,d,f,h)}else f(null)}var f={},h={};a.g={get:function(a,c){var e=h.hasOwnProperty(a)?h[a]:b;e?setTimeout(function(){c(e)},0):d(a,c)},qb:function(a){delete h[a]},gb:e};a.g.loaders=[];a.b("components",a.g);a.b("components.get",a.g.get);a.b("components.clearCachedDefinition",a.g.qb)})();(function(){function b(b,
d,e,f){function q(){0===--r&&f(m)}var m={},r=2,s=e.template;e=e.viewModel;s?c(d,s,function(c){a.g.gb("loadTemplate",[b,c],function(a){m.template=a;q()})}):q();e?c(d,e,function(c){a.g.gb("loadViewModel",[b,c],function(a){m[h]=a;q()})}):q()}function d(a,b,c){if("function"===typeof b)c(function(a){return new b(a)});else if("function"===typeof b[h])c(b[h]);else if("instance"in b){var e=b.instance;c(function(){return e})}else"viewModel"in b?d(a,b.viewModel,c):a("Unknown viewModel value: "+b)}function c(a,
b,c){"string"===typeof b.require?N||z.require?(N||z.require)([b.require],c):a("Uses require, but no AMD loader is present"):c(b)}function e(a){return function(b){throw Error("Component '"+a+"': "+b);}}var f={};a.g.qc=function(b,c){if(!c)throw Error("Invalid configuration for "+b);if(a.g.Qa(b))throw Error("Component "+b+" is already registered");f[b]=c};a.g.Qa=function(a){return a in f};a.g.tc=function(b){delete f[b];a.g.qb(b)};a.g.rb={getConfig:function(a,b){b(f.hasOwnProperty(a)?f[a]:null)},loadComponent:function(a,
d,f){var h=e(a);c(h,d,function(c){b(a,h,c,f)})},loadTemplate:function(b,c,d){b=e(b);if("string"===typeof c)d(a.a.ta(c));else if(c instanceof Array)d(c);else if(z.DocumentFragment?c instanceof DocumentFragment:c&&11===c.nodeType)d(a.a.R(c.childNodes));else if(c.element)if(c=c.element,z.HTMLElement?c instanceof HTMLElement:c&&c.tagName&&1===c.nodeType)d(a.a.fa(c.childNodes));else if("string"===typeof c){var f=x.getElementById(c);f?d(a.a.fa(f.childNodes)):b("Cannot find element with ID "+c)}else b("Unknown element type: "+
c);else b("Unknown template value: "+c)},loadViewModel:function(a,b,c){d(e(a),b,c)}};var h="createViewModel";a.b("components.register",a.g.qc);a.b("components.isRegistered",a.g.Qa);a.b("components.unregister",a.g.tc);a.b("components.defaultLoader",a.g.rb);a.g.loaders.push(a.g.rb);a.g.Qb=f})();(function(){function b(b,e){var f=b.getAttribute("params");if(f){var f=d.parseBindingsString(f,e,b,{valueAccessors:!0,bindingParams:!0}),f=a.a.la(f,function(d){return a.L(d,null,{t:b})}),h=a.a.la(f,function(d){return d.W()?
a.L(function(){return a.a.c(d())},null,{t:b}):d.o()});h.hasOwnProperty("$raw")||(h.$raw=f);return h}return null}a.g.getComponentNameForNode=function(b){b=a.a.A(b);return a.g.Qa(b)&&b};a.g.jb=function(c,d,f,h){if(1===d.nodeType){var g=a.g.getComponentNameForNode(d);if(g){c=c||{};if(c.component)throw Error('Cannot use the "component" binding on a custom element matching a component');var k={name:g,params:b(d,f)};c.component=h?function(){return k}:k}}return c};var d=new a.H;9>a.a.ka&&(a.g.register=function(a){return function(b){x.createElement(b);
return a.apply(this,arguments)}}(a.g.register),x.createDocumentFragment=function(b){return function(){var d=b(),f=a.g.Qb,h;for(h in f)f.hasOwnProperty(h)&&d.createElement(h);return d}}(x.createDocumentFragment))})();(function(){var b=0;a.d.component={init:function(d,c,e,f,h){function g(){var a=k&&k.dispose;"function"===typeof a&&a.call(k);l=null}var k,l;a.a.u.aa(d,g);a.L(function(){var e=a.a.c(c()),f,m;"string"===typeof e?f=e:(f=a.a.c(e.name),m=a.a.c(e.params));if(!f)throw Error("No component name specified");
var r=l=++b;a.g.get(f,function(b){if(l===r){g();if(!b)throw Error("Unknown component '"+f+"'");var c=b.template;if(!c)throw Error("Component '"+f+"' has no template");c=a.a.fa(c);a.e.S(d,c);var c=m,e=b.createViewModel;b=e?e.call(b,c,{element:d}):c;c=h.createChildContext(b);k=b;a.Ca(c,d)}})},null,{t:d});return{controlsDescendantBindings:!0}}};a.e.P.component=!0})();var O={"class":"className","for":"htmlFor"};a.d.attr={update:function(b,d){var c=a.a.c(d())||{};a.a.D(c,function(c,d){d=a.a.c(d);var h=
!1===d||null===d||d===p;h&&b.removeAttribute(c);8>=a.a.ka&&c in O?(c=O[c],h?b.removeAttribute(c):b[c]=d):h||b.setAttribute(c,d.toString());"name"===c&&a.a.Ib(b,h?"":d.toString())})}};(function(){a.d.checked={after:["value","attr"],init:function(b,d,c){function e(){return c.has("checkedValue")?a.a.c(c.get("checkedValue")):b.value}function f(){var g=b.checked,f=q?e():g;if(!a.ga.sa()&&(!k||g)){var h=a.l.w(d);l?n!==f?(g&&(a.a.ba(h,f,!0),a.a.ba(h,n,!1)),n=f):a.a.ba(h,f,g):a.h.za(h,c,"checked",f,!0)}}function h(){var c=
a.a.c(d());b.checked=l?0<=a.a.m(c,e()):g?c:e()===c}var g="checkbox"==b.type,k="radio"==b.type;if(g||k){var l=g&&a.a.c(d())instanceof Array,n=l?e():p,q=k||l;k&&!b.name&&a.d.uniqueName.init(b,function(){return!0});a.L(f,null,{t:b});a.a.r(b,"click",f);a.L(h,null,{t:b})}}};a.h.Z.checked=!0;a.d.checkedValue={update:function(b,d){b.value=a.a.c(d())}}})();a.d.css={update:function(b,d){var c=a.a.c(d());"object"==typeof c?a.a.D(c,function(c,d){d=a.a.c(d);a.a.ya(b,c,d)}):(c=String(c||""),a.a.ya(b,b.__ko__cssValue,
!1),b.__ko__cssValue=c,a.a.ya(b,c,!0))}};a.d.enable={update:function(b,d){var c=a.a.c(d());c&&b.disabled?b.removeAttribute("disabled"):c||b.disabled||(b.disabled=!0)}};a.d.disable={update:function(b,d){a.d.enable.update(b,function(){return!a.a.c(d())})}};a.d.event={init:function(b,d,c,e,f){var h=d()||{};a.a.D(h,function(g){"string"==typeof g&&a.a.r(b,g,function(b){var h,n=d()[g];if(n){try{var q=a.a.R(arguments);e=f.$data;q.unshift(e);h=n.apply(e,q)}finally{!0!==h&&(b.preventDefault?b.preventDefault():
b.returnValue=!1)}!1===c.get(g+"Bubble")&&(b.cancelBubble=!0,b.stopPropagation&&b.stopPropagation())}})})}};a.d.foreach={Bb:function(b){return function(){var d=b(),c=a.a.Wa(d);if(!c||"number"==typeof c.length)return{foreach:d,templateEngine:a.M.Oa};a.a.c(d);return{foreach:c.data,as:c.as,includeDestroyed:c.includeDestroyed,afterAdd:c.afterAdd,beforeRemove:c.beforeRemove,afterRender:c.afterRender,beforeMove:c.beforeMove,afterMove:c.afterMove,templateEngine:a.M.Oa}}},init:function(b,d){return a.d.template.init(b,
a.d.foreach.Bb(d))},update:function(b,d,c,e,f){return a.d.template.update(b,a.d.foreach.Bb(d),c,e,f)}};a.h.ea.foreach=!1;a.e.P.foreach=!0;a.d.hasfocus={init:function(b,d,c){function e(g){b.__ko_hasfocusUpdating=!0;var e=b.ownerDocument;if("activeElement"in e){var f;try{f=e.activeElement}catch(h){f=e.body}g=f===b}e=d();a.h.za(e,c,"hasfocus",g,!0);b.__ko_hasfocusLastValue=g;b.__ko_hasfocusUpdating=!1}var f=e.bind(null,!0),h=e.bind(null,!1);a.a.r(b,"focus",f);a.a.r(b,"focusin",f);a.a.r(b,"blur",h);a.a.r(b,
"focusout",h)},update:function(b,d){var c=!!a.a.c(d());b.__ko_hasfocusUpdating||b.__ko_hasfocusLastValue===c||(c?b.focus():b.blur(),a.l.w(a.a.ma,null,[b,c?"focusin":"focusout"]))}};a.h.Z.hasfocus=!0;a.d.hasFocus=a.d.hasfocus;a.h.Z.hasFocus=!0;a.d.html={init:function(){return{controlsDescendantBindings:!0}},update:function(b,d){a.a.Za(b,d())}};I("if");I("ifnot",!1,!0);I("with",!0,!1,function(a,d){return a.createChildContext(d)});var K={};a.d.options={init:function(b){if("select"!==a.a.A(b))throw Error("options binding applies only to SELECT elements");
for(;0<b.length;)b.remove(0);return{controlsDescendantBindings:!0}},update:function(b,d,c){function e(){return a.a.pa(b.options,function(a){return a.selected})}function f(a,b,c){var d=typeof b;return"function"==d?b(a):"string"==d?a[b]:c}function h(c,d){if(q.length){var g=0<=a.a.m(q,a.j.q(d[0]));a.a.Jb(d[0],g);m&&!g&&a.l.w(a.a.ma,null,[b,"change"])}}var g=0!=b.length&&b.multiple?b.scrollTop:null,k=a.a.c(d()),l=c.get("optionsIncludeDestroyed");d={};var n,q;q=b.multiple?a.a.Da(e(),a.j.q):0<=b.selectedIndex?
[a.j.q(b.options[b.selectedIndex])]:[];k&&("undefined"==typeof k.length&&(k=[k]),n=a.a.pa(k,function(b){return l||b===p||null===b||!a.a.c(b._destroy)}),c.has("optionsCaption")&&(k=a.a.c(c.get("optionsCaption")),null!==k&&k!==p&&n.unshift(K)));var m=!1;d.beforeRemove=function(a){b.removeChild(a)};k=h;c.has("optionsAfterRender")&&(k=function(b,d){h(0,d);a.l.w(c.get("optionsAfterRender"),null,[d[0],b!==K?b:p])});a.a.Ya(b,n,function(d,g,e){e.length&&(q=e[0].selected?[a.j.q(e[0])]:[],m=!0);g=b.ownerDocument.createElement("option");
d===K?(a.a.ab(g,c.get("optionsCaption")),a.j.$(g,p)):(e=f(d,c.get("optionsValue"),d),a.j.$(g,a.a.c(e)),d=f(d,c.get("optionsText"),e),a.a.ab(g,d));return[g]},d,k);a.l.w(function(){c.get("valueAllowUnset")&&c.has("value")?a.j.$(b,a.a.c(c.get("value")),!0):(b.multiple?q.length&&e().length<q.length:q.length&&0<=b.selectedIndex?a.j.q(b.options[b.selectedIndex])!==q[0]:q.length||0<=b.selectedIndex)&&a.a.ma(b,"change")});a.a.$b(b);g&&20<Math.abs(g-b.scrollTop)&&(b.scrollTop=g)}};a.d.options.Ua=a.a.f.N();
a.d.selectedOptions={after:["options","foreach"],init:function(b,d,c){a.a.r(b,"change",function(){var e=d(),f=[];a.a.s(b.getElementsByTagName("option"),function(b){b.selected&&f.push(a.j.q(b))});a.h.za(e,c,"selectedOptions",f)})},update:function(b,d){if("select"!=a.a.A(b))throw Error("values binding applies only to SELECT elements");var c=a.a.c(d());c&&"number"==typeof c.length&&a.a.s(b.getElementsByTagName("option"),function(b){var d=0<=a.a.m(c,a.j.q(b));a.a.Jb(b,d)})}};a.h.Z.selectedOptions=!0;
a.d.style={update:function(b,d){var c=a.a.c(d()||{});a.a.D(c,function(c,d){d=a.a.c(d);b.style[c]=d||""})}};a.d.submit={init:function(b,d,c,e,f){if("function"!=typeof d())throw Error("The value for a submit binding must be a function");a.a.r(b,"submit",function(a){var c,e=d();try{c=e.call(f.$data,b)}finally{!0!==c&&(a.preventDefault?a.preventDefault():a.returnValue=!1)}})}};a.d.text={init:function(){return{controlsDescendantBindings:!0}},update:function(b,d){a.a.ab(b,d())}};a.e.P.text=!0;a.d.uniqueName=
{init:function(b,d){if(d()){var c="ko_unique_"+ ++a.d.uniqueName.Vb;a.a.Ib(b,c)}}};a.d.uniqueName.Vb=0;a.d.value={after:["options","foreach"],init:function(b,d,c){function e(){g=!1;var e=d(),f=a.j.q(b);a.h.za(e,c,"value",f)}var f=["change"],h=c.get("valueUpdate"),g=!1;h&&("string"==typeof h&&(h=[h]),a.a.da(f,h),f=a.a.nb(f));!a.a.ka||"input"!=b.tagName.toLowerCase()||"text"!=b.type||"off"==b.autocomplete||b.form&&"off"==b.form.autocomplete||-1!=a.a.m(f,"propertychange")||(a.a.r(b,"propertychange",
function(){g=!0}),a.a.r(b,"focus",function(){g=!1}),a.a.r(b,"blur",function(){g&&e()}));a.a.s(f,function(c){var d=e;a.a.sc(c,"after")&&(d=function(){setTimeout(e,0)},c=c.substring(5));a.a.r(b,c,d)})},update:function(b,d,c){var e=a.a.c(d());d=a.j.q(b);if(e!==d)if("select"===a.a.A(b)){var f=c.get("valueAllowUnset");c=function(){a.j.$(b,e,f)};c();f||e===a.j.q(b)?setTimeout(c,0):a.l.w(a.a.ma,null,[b,"change"])}else a.j.$(b,e)}};a.h.Z.value=!0;a.d.visible={update:function(b,d){var c=a.a.c(d()),e="none"!=
b.style.display;c&&!e?b.style.display="":!c&&e&&(b.style.display="none")}};(function(b){a.d[b]={init:function(d,c,e,f,h){return a.d.event.init.call(this,d,function(){var a={};a[b]=c();return a},e,f,h)}}})("click");a.F=function(){};a.F.prototype.renderTemplateSource=function(){throw Error("Override renderTemplateSource");};a.F.prototype.createJavaScriptEvaluatorBlock=function(){throw Error("Override createJavaScriptEvaluatorBlock");};a.F.prototype.makeTemplateSource=function(b,d){if("string"==typeof b){d=
d||x;var c=d.getElementById(b);if(!c)throw Error("Cannot find template with ID "+b);return new a.p.k(c)}if(1==b.nodeType||8==b.nodeType)return new a.p.ca(b);throw Error("Unknown template type: "+b);};a.F.prototype.renderTemplate=function(a,d,c,e){a=this.makeTemplateSource(a,e);return this.renderTemplateSource(a,d,c)};a.F.prototype.isTemplateRewritten=function(a,d){return!1===this.allowTemplateRewriting?!0:this.makeTemplateSource(a,d).data("isRewritten")};a.F.prototype.rewriteTemplate=function(a,d,
c){a=this.makeTemplateSource(a,c);d=d(a.text());a.text(d);a.data("isRewritten",!0)};a.b("templateEngine",a.F);a.cb=function(){function b(b,c,d,g){b=a.h.Va(b);for(var k=a.h.ea,l=0;l<b.length;l++){var n=b[l].key;if(k.hasOwnProperty(n)){var q=k[n];if("function"===typeof q){if(n=q(b[l].value))throw Error(n);}else if(!q)throw Error("This template engine does not support the '"+n+"' binding within its templates");}}d="ko.__tr_ambtns(function($context,$element){return(function(){return{ "+a.h.ua(b,{valueAccessors:!0})+
" } })()},'"+d.toLowerCase()+"')";return g.createJavaScriptEvaluatorBlock(d)+c}var d=/(<([a-z]+\d*)(?:\s+(?!data-bind\s*=\s*)[a-z0-9\-]+(?:=(?:\"[^\"]*\"|\'[^\']*\'))?)*\s+)data-bind\s*=\s*(["'])([\s\S]*?)\3/gi,c=/\x3c!--\s*ko\b\s*([\s\S]*?)\s*--\x3e/g;return{ac:function(b,c,d){c.isTemplateRewritten(b,d)||c.rewriteTemplate(b,function(b){return a.cb.kc(b,c)},d)},kc:function(a,f){return a.replace(d,function(a,c,d,e,n){return b(n,c,d,f)}).replace(c,function(a,c){return b(c,"\x3c!-- ko --\x3e","#comment",
f)})},Tb:function(b,c){return a.C.Ta(function(d,g){var k=d.nextSibling;k&&k.nodeName.toLowerCase()===c&&a.Ba(k,b,g)})}}}();a.b("__tr_ambtns",a.cb.Tb);(function(){a.p={};a.p.k=function(a){this.k=a};a.p.k.prototype.text=function(){var b=a.a.A(this.k),b="script"===b?"text":"textarea"===b?"value":"innerHTML";if(0==arguments.length)return this.k[b];var d=arguments[0];"innerHTML"===b?a.a.Za(this.k,d):this.k[b]=d};var b=a.a.f.N()+"_";a.p.k.prototype.data=function(c){if(1===arguments.length)return a.a.f.get(this.k,
b+c);a.a.f.set(this.k,b+c,arguments[1])};var d=a.a.f.N();a.p.ca=function(a){this.k=a};a.p.ca.prototype=new a.p.k;a.p.ca.prototype.text=function(){if(0==arguments.length){var b=a.a.f.get(this.k,d)||{};b.eb===p&&b.Ga&&(b.eb=b.Ga.innerHTML);return b.eb}a.a.f.set(this.k,d,{eb:arguments[0]})};a.p.k.prototype.nodes=function(){if(0==arguments.length)return(a.a.f.get(this.k,d)||{}).Ga;a.a.f.set(this.k,d,{Ga:arguments[0]})};a.b("templateSources",a.p);a.b("templateSources.domElement",a.p.k);a.b("templateSources.anonymousTemplate",
a.p.ca)})();(function(){function b(b,c,d){var e;for(c=a.e.nextSibling(c);b&&(e=b)!==c;)b=a.e.nextSibling(e),d(e,b)}function d(c,d){if(c.length){var e=c[0],f=c[c.length-1],h=e.parentNode,m=a.H.instance,r=m.preprocessNode;if(r){b(e,f,function(a,b){var c=a.previousSibling,d=r.call(m,a);d&&(a===e&&(e=d[0]||b),a===f&&(f=d[d.length-1]||c))});c.length=0;if(!e)return;e===f?c.push(e):(c.push(e,f),a.a.ia(c,h))}b(e,f,function(b){1!==b.nodeType&&8!==b.nodeType||a.lb(d,b)});b(e,f,function(b){1!==b.nodeType&&8!==
b.nodeType||a.C.Ob(b,[d])});a.a.ia(c,h)}}function c(a){return a.nodeType?a:0<a.length?a[0]:null}function e(b,e,h,n,q){q=q||{};var m=b&&c(b),m=m&&m.ownerDocument,r=q.templateEngine||f;a.cb.ac(h,r,m);h=r.renderTemplate(h,n,q,m);if("number"!=typeof h.length||0<h.length&&"number"!=typeof h[0].nodeType)throw Error("Template engine must return an array of DOM nodes");m=!1;switch(e){case "replaceChildren":a.e.S(b,h);m=!0;break;case "replaceNode":a.a.Hb(b,h);m=!0;break;case "ignoreTargetNode":break;default:throw Error("Unknown renderMode: "+
e);}m&&(d(h,n),q.afterRender&&a.l.w(q.afterRender,null,[h,n.$data]));return h}var f;a.$a=function(b){if(b!=p&&!(b instanceof a.F))throw Error("templateEngine must inherit from ko.templateEngine");f=b};a.Xa=function(b,d,h,n,q){h=h||{};if((h.templateEngine||f)==p)throw Error("Set a template engine before calling renderTemplate");q=q||"replaceChildren";if(n){var m=c(n);return a.i(function(){var f=d&&d instanceof a.K?d:new a.K(a.a.c(d)),p=a.B(b)?b():"function"==typeof b?b(f.$data,f):b,f=e(n,q,p,f,h);
"replaceNode"==q&&(n=f,m=c(n))},null,{Ia:function(){return!m||!a.a.Ja(m)},t:m&&"replaceNode"==q?m.parentNode:m})}return a.C.Ta(function(c){a.Xa(b,d,h,c,"replaceNode")})};a.rc=function(b,c,f,h,q){function m(a,b){d(b,s);f.afterRender&&f.afterRender(b,a)}function r(a,c){s=q.createChildContext(a,f.as,function(a){a.$index=c});var d="function"==typeof b?b(a,s):b;return e(null,"ignoreTargetNode",d,s,f)}var s;return a.i(function(){var b=a.a.c(c)||[];"undefined"==typeof b.length&&(b=[b]);b=a.a.pa(b,function(b){return f.includeDestroyed||
b===p||null===b||!a.a.c(b._destroy)});a.l.w(a.a.Ya,null,[h,b,r,f,m])},null,{t:h})};var h=a.a.f.N();a.d.template={init:function(b,c){var d=a.a.c(c());"string"==typeof d||d.name?a.e.ha(b):(d=a.e.childNodes(b),d=a.a.lc(d),(new a.p.ca(b)).nodes(d));return{controlsDescendantBindings:!0}},update:function(b,c,d,e,f){var m=c(),r;c=a.a.c(m);d=!0;e=null;"string"==typeof c?c={}:(m=c.name,"if"in c&&(d=a.a.c(c["if"])),d&&"ifnot"in c&&(d=!a.a.c(c.ifnot)),r=a.a.c(c.data));"foreach"in c?e=a.rc(m||b,d&&c.foreach||
[],c,b,f):d?(f="data"in c?f.createChildContext(r,c.as):f,e=a.Xa(m||b,f,c,b)):a.e.ha(b);f=e;(r=a.a.f.get(b,h))&&"function"==typeof r.I&&r.I();a.a.f.set(b,h,f&&f.W()?f:p)}};a.h.ea.template=function(b){b=a.h.Va(b);return 1==b.length&&b[0].unknown||a.h.ic(b,"name")?null:"This template engine does not support anonymous templates nested within its templates"};a.e.P.template=!0})();a.b("setTemplateEngine",a.$a);a.b("renderTemplate",a.Xa);a.a.tb=function(a,d,c){if(a.length&&d.length){var e,f,h,g,k;for(e=
f=0;(!c||e<c)&&(g=a[f]);++f){for(h=0;k=d[h];++h)if(g.value===k.value){g.moved=k.index;k.moved=g.index;d.splice(h,1);e=h=0;break}e+=h}}};a.a.Fa=function(){function b(b,c,e,f,h){var g=Math.min,k=Math.max,l=[],n,q=b.length,m,r=c.length,p=r-q||1,u=q+r+1,v,t,x;for(n=0;n<=q;n++)for(t=v,l.push(v=[]),x=g(r,n+p),m=k(0,n-1);m<=x;m++)v[m]=m?n?b[n-1]===c[m-1]?t[m-1]:g(t[m]||u,v[m-1]||u)+1:m+1:n+1;g=[];k=[];p=[];n=q;for(m=r;n||m;)r=l[n][m]-1,m&&r===l[n][m-1]?k.push(g[g.length]={status:e,value:c[--m],index:m}):
n&&r===l[n-1][m]?p.push(g[g.length]={status:f,value:b[--n],index:n}):(--m,--n,h.sparse||g.push({status:"retained",value:c[m]}));a.a.tb(k,p,10*q);return g.reverse()}return function(a,c,e){e="boolean"===typeof e?{dontLimitMoves:e}:e||{};a=a||[];c=c||[];return a.length<=c.length?b(a,c,"added","deleted",e):b(c,a,"deleted","added",e)}}();a.b("utils.compareArrays",a.a.Fa);(function(){function b(b,d,f,h,g){var k=[],l=a.i(function(){var l=d(f,g,a.a.ia(k,b))||[];0<k.length&&(a.a.Hb(k,l),h&&a.l.w(h,null,[f,
l,g]));k.length=0;a.a.da(k,l)},null,{t:b,Ia:function(){return!a.a.kb(k)}});return{X:k,i:l.W()?l:p}}var d=a.a.f.N();a.a.Ya=function(c,e,f,h,g){function k(b,d){w=q[d];v!==d&&(z[b]=w);w.Na(v++);a.a.ia(w.X,c);s.push(w);x.push(w)}function l(b,c){if(b)for(var d=0,e=c.length;d<e;d++)c[d]&&a.a.s(c[d].X,function(a){b(a,d,c[d].oa)})}e=e||[];h=h||{};var n=a.a.f.get(c,d)===p,q=a.a.f.get(c,d)||[],m=a.a.Da(q,function(a){return a.oa}),r=a.a.Fa(m,e,h.dontLimitMoves),s=[],u=0,v=0,t=[],x=[];e=[];for(var z=[],m=[],
w,y=0,A,C;A=r[y];y++)switch(C=A.moved,A.status){case "deleted":C===p&&(w=q[u],w.i&&w.i.I(),t.push.apply(t,a.a.ia(w.X,c)),h.beforeRemove&&(e[y]=w,x.push(w)));u++;break;case "retained":k(y,u++);break;case "added":C!==p?k(y,C):(w={oa:A.value,Na:a.n(v++)},s.push(w),x.push(w),n||(m[y]=w))}l(h.beforeMove,z);a.a.s(t,h.beforeRemove?a.Q:a.removeNode);for(var y=0,n=a.e.firstChild(c),E;w=x[y];y++){w.X||a.a.extend(w,b(c,f,w.oa,g,w.Na));for(u=0;r=w.X[u];n=r.nextSibling,E=r,u++)r!==n&&a.e.xb(c,r,E);!w.fc&&g&&(g(w.oa,
w.X,w.Na),w.fc=!0)}l(h.beforeRemove,e);l(h.afterMove,z);l(h.afterAdd,m);a.a.f.set(c,d,s)}})();a.b("utils.setDomNodeChildrenFromArrayMapping",a.a.Ya);a.M=function(){this.allowTemplateRewriting=!1};a.M.prototype=new a.F;a.M.prototype.renderTemplateSource=function(b){var d=(9>a.a.ka?0:b.nodes)?b.nodes():null;if(d)return a.a.R(d.cloneNode(!0).childNodes);b=b.text();return a.a.ta(b)};a.M.Oa=new a.M;a.$a(a.M.Oa);a.b("nativeTemplateEngine",a.M);(function(){a.Ra=function(){var a=this.hc=function(){if(!t||
!t.tmpl)return 0;try{if(0<=t.tmpl.tag.tmpl.open.toString().indexOf("__"))return 2}catch(a){}return 1}();this.renderTemplateSource=function(b,e,f){f=f||{};if(2>a)throw Error("Your version of jQuery.tmpl is too old. Please upgrade to jQuery.tmpl 1.0.0pre or later.");var h=b.data("precompiled");h||(h=b.text()||"",h=t.template(null,"{{ko_with $item.koBindingContext}}"+h+"{{/ko_with}}"),b.data("precompiled",h));b=[e.$data];e=t.extend({koBindingContext:e},f.templateOptions);e=t.tmpl(h,b,e);e.appendTo(x.createElement("div"));
t.fragments={};return e};this.createJavaScriptEvaluatorBlock=function(a){return"{{ko_code ((function() { return "+a+" })()) }}"};this.addTemplate=function(a,b){x.write("<script type='text/html' id='"+a+"'>"+b+"\x3c/script>")};0<a&&(t.tmpl.tag.ko_code={open:"__.push($1 || '');"},t.tmpl.tag.ko_with={open:"with($1) {",close:"} "})};a.Ra.prototype=new a.F;var b=new a.Ra;0<b.hc&&a.$a(b);a.b("jqueryTmplTemplateEngine",a.Ra)})()})})();})();
