/*!
 * Knockout JavaScript library v3.1.0
 * (c) Steven Sanderson - http://knockoutjs.com/
 * License: MIT (http://www.opensource.org/licenses/mit-license.php)
 */

(function() {(function(p){var y=this||(0,eval)("this"),w=y.document,K=y.navigator,t=y.jQuery,C=y.JSON;(function(p){"function"===typeof require&&"object"===typeof exports&&"object"===typeof module?p(module.exports||exports,require):"function"===typeof define&&define.amd?define(["exports","require"],p):p(y.ko={})})(function(L,M){function G(a,c){return null===a||typeof a in O?a===c:!1}function P(a,c){var d;return function(){d||(d=setTimeout(function(){d=p;a()},c))}}function Q(a,c){var d;return function(){clearTimeout(d);
d=setTimeout(a,c)}}function H(b,c,d,e){a.d[b]={init:function(b,h,g,k,l){var n,s;a.da(function(){var k=a.a.c(h()),g=!d!==!k,r=!s;if(r||c||g!==n)r&&a.ea.ha()&&(s=a.a.nb(a.e.childNodes(b),!0)),g?(r||a.e.R(b,a.a.nb(s)),a.Aa(e?e(l,k):l,b)):a.e.fa(b),n=g},null,{H:b});return{controlsDescendantBindings:!0}}};a.g.ca[b]=!1;a.e.O[b]=!0}var a="undefined"!==typeof L?L:{};a.b=function(b,c){for(var d=b.split("."),e=a,f=0;f<d.length-1;f++)e=e[d[f]];e[d[d.length-1]]=c};a.u=function(a,c,d){a[c]=d};a.version="3.1.0";
a.b("version",a.version);a.a=function(){function b(a,b){for(var c in a)a.hasOwnProperty(c)&&b(c,a[c])}function c(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a}function d(a,b){a.__proto__=b;return a}var e={__proto__:[]}instanceof Array,f={},h={};f[K&&/Firefox\/2/i.test(K.userAgent)?"KeyboardEvent":"UIEvents"]=["keyup","keydown","keypress"];f.MouseEvents="click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave".split(" ");b(f,function(a,b){if(b.length)for(var c=
0,d=b.length;c<d;c++)h[b[c]]=a});var g={propertychange:!0},k=w&&function(){for(var a=3,b=w.createElement("div"),c=b.getElementsByTagName("i");b.innerHTML="\x3c!--[if gt IE "+ ++a+"]><i></i><![endif]--\x3e",c[0];);return 4<a?a:p}();return{pb:["authenticity_token",/^__RequestVerificationToken(_.*)?$/],s:function(a,b){for(var c=0,d=a.length;c<d;c++)b(a[c],c)},m:function(a,b){if("function"==typeof Array.prototype.indexOf)return Array.prototype.indexOf.call(a,b);for(var c=0,d=a.length;c<d;c++)if(a[c]===
b)return c;return-1},ib:function(a,b,c){for(var d=0,k=a.length;d<k;d++)if(b.call(c,a[d],d))return a[d];return null},na:function(l,b){var c=a.a.m(l,b);0<c?l.splice(c,1):0===c&&l.shift()},jb:function(l){l=l||[];for(var b=[],c=0,d=l.length;c<d;c++)0>a.a.m(b,l[c])&&b.push(l[c]);return b},Ba:function(a,b){a=a||[];for(var c=[],d=0,k=a.length;d<k;d++)c.push(b(a[d],d));return c},ma:function(a,b){a=a||[];for(var c=[],d=0,k=a.length;d<k;d++)b(a[d],d)&&c.push(a[d]);return c},ba:function(a,b){if(b instanceof
Array)a.push.apply(a,b);else for(var c=0,d=b.length;c<d;c++)a.push(b[c]);return a},$:function(l,b,c){var d=a.a.m(a.a.Ua(l),b);0>d?c&&l.push(b):c||l.splice(d,1)},oa:e,extend:c,ta:d,ua:e?d:c,B:b,Ra:function(a,b){if(!a)return a;var c={},d;for(d in a)a.hasOwnProperty(d)&&(c[d]=b(a[d],d,a));return c},Ia:function(l){for(;l.firstChild;)a.removeNode(l.firstChild)},ic:function(l){l=a.a.Q(l);for(var b=w.createElement("div"),c=0,d=l.length;c<d;c++)b.appendChild(a.P(l[c]));return b},nb:function(l,b){for(var c=
0,d=l.length,k=[];c<d;c++){var g=l[c].cloneNode(!0);k.push(b?a.P(g):g)}return k},R:function(b,c){a.a.Ia(b);if(c)for(var d=0,k=c.length;d<k;d++)b.appendChild(c[d])},Fb:function(b,c){var d=b.nodeType?[b]:b;if(0<d.length){for(var k=d[0],g=k.parentNode,e=0,f=c.length;e<f;e++)g.insertBefore(c[e],k);e=0;for(f=d.length;e<f;e++)a.removeNode(d[e])}},ga:function(a,b){if(a.length){for(b=8===b.nodeType&&b.parentNode||b;a.length&&a[0].parentNode!==b;)a.shift();if(1<a.length){var c=a[0],d=a[a.length-1];for(a.length=
0;c!==d;)if(a.push(c),c=c.nextSibling,!c)return;a.push(d)}}return a},Hb:function(a,b){7>k?a.setAttribute("selected",b):a.selected=b},va:function(a){return null===a||a===p?"":a.trim?a.trim():a.toString().replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},wc:function(b,c){for(var d=[],k=(b||"").split(c),e=0,g=k.length;e<g;e++){var f=a.a.va(k[e]);""!==f&&d.push(f)}return d},pc:function(a,b){a=a||"";return b.length>a.length?!1:a.substring(0,b.length)===b},Wb:function(a,b){if(a===b)return!0;if(11===a.nodeType)return!1;
if(b.contains)return b.contains(3===a.nodeType?a.parentNode:a);if(b.compareDocumentPosition)return 16==(b.compareDocumentPosition(a)&16);for(;a&&a!=b;)a=a.parentNode;return!!a},Ha:function(b){return a.a.Wb(b,b.ownerDocument.documentElement)},gb:function(b){return!!a.a.ib(b,a.a.Ha)},C:function(a){return a&&a.tagName&&a.tagName.toLowerCase()},r:function(b,c,d){var e=k&&g[c];if(!e&&t)t(b).bind(c,d);else if(e||"function"!=typeof b.addEventListener)if("undefined"!=typeof b.attachEvent){var f=function(a){d.call(b,
a)},h="on"+c;b.attachEvent(h,f);a.a.t.Z(b,function(){b.detachEvent(h,f)})}else throw Error("Browser doesn't support addEventListener or attachEvent");else b.addEventListener(c,d,!1)},ja:function(b,c){if(!b||!b.nodeType)throw Error("element must be a DOM node when calling triggerEvent");var d;"input"===a.a.C(b)&&b.type&&"click"==c.toLowerCase()?(d=b.type,d="checkbox"==d||"radio"==d):d=!1;if(t&&!d)t(b).trigger(c);else if("function"==typeof w.createEvent)if("function"==typeof b.dispatchEvent)d=w.createEvent(h[c]||
"HTMLEvents"),d.initEvent(c,!0,!0,y,0,0,0,0,0,!1,!1,!1,!1,0,b),b.dispatchEvent(d);else throw Error("The supplied element doesn't support dispatchEvent");else if(d&&b.click)b.click();else if("undefined"!=typeof b.fireEvent)b.fireEvent("on"+c);else throw Error("Browser doesn't support triggering events");},c:function(b){return a.w(b)?b():b},Ua:function(b){return a.w(b)?b.p():b},wa:function(b,c,d){if(c){var k=/\S+/g,e=b.className.match(k)||[];a.a.s(c.match(k),function(b){a.a.$(e,b,d)});b.className=e.join(" ")}},
Za:function(b,c){var d=a.a.c(c);if(null===d||d===p)d="";var k=a.e.firstChild(b);!k||3!=k.nodeType||a.e.nextSibling(k)?a.e.R(b,[b.ownerDocument.createTextNode(d)]):k.data=d;a.a.Zb(b)},Gb:function(a,b){a.name=b;if(7>=k)try{a.mergeAttributes(w.createElement("<input name='"+a.name+"'/>"),!1)}catch(c){}},Zb:function(a){9<=k&&(a=1==a.nodeType?a:a.parentNode,a.style&&(a.style.zoom=a.style.zoom))},Xb:function(a){if(k){var b=a.style.width;a.style.width=0;a.style.width=b}},mc:function(b,c){b=a.a.c(b);c=a.a.c(c);
for(var d=[],k=b;k<=c;k++)d.push(k);return d},Q:function(a){for(var b=[],c=0,d=a.length;c<d;c++)b.push(a[c]);return b},uc:6===k,vc:7===k,pa:k,rb:function(b,c){for(var d=a.a.Q(b.getElementsByTagName("input")).concat(a.a.Q(b.getElementsByTagName("textarea"))),k="string"==typeof c?function(a){return a.name===c}:function(a){return c.test(a.name)},e=[],g=d.length-1;0<=g;g--)k(d[g])&&e.push(d[g]);return e},jc:function(b){return"string"==typeof b&&(b=a.a.va(b))?C&&C.parse?C.parse(b):(new Function("return "+
b))():null},$a:function(b,c,d){if(!C||!C.stringify)throw Error("Cannot find JSON.stringify(). Some browsers (e.g., IE < 8) don't support it natively, but you can overcome this by adding a script reference to json2.js, downloadable from http://www.json.org/json2.js");return C.stringify(a.a.c(b),c,d)},kc:function(c,d,k){k=k||{};var e=k.params||{},g=k.includeFields||this.pb,f=c;if("object"==typeof c&&"form"===a.a.C(c))for(var f=c.action,h=g.length-1;0<=h;h--)for(var u=a.a.rb(c,g[h]),D=u.length-1;0<=
D;D--)e[u[D].name]=u[D].value;d=a.a.c(d);var z=w.createElement("form");z.style.display="none";z.action=f;z.method="post";for(var p in d)c=w.createElement("input"),c.name=p,c.value=a.a.$a(a.a.c(d[p])),z.appendChild(c);b(e,function(a,b){var c=w.createElement("input");c.name=a;c.value=b;z.appendChild(c)});w.body.appendChild(z);k.submitter?k.submitter(z):z.submit();setTimeout(function(){z.parentNode.removeChild(z)},0)}}}();a.b("utils",a.a);a.b("utils.arrayForEach",a.a.s);a.b("utils.arrayFirst",a.a.ib);
a.b("utils.arrayFilter",a.a.ma);a.b("utils.arrayGetDistinctValues",a.a.jb);a.b("utils.arrayIndexOf",a.a.m);a.b("utils.arrayMap",a.a.Ba);a.b("utils.arrayPushAll",a.a.ba);a.b("utils.arrayRemoveItem",a.a.na);a.b("utils.extend",a.a.extend);a.b("utils.fieldsIncludedWithJsonPost",a.a.pb);a.b("utils.getFormFields",a.a.rb);a.b("utils.peekObservable",a.a.Ua);a.b("utils.postJson",a.a.kc);a.b("utils.parseJson",a.a.jc);a.b("utils.registerEventHandler",a.a.r);a.b("utils.stringifyJson",a.a.$a);a.b("utils.range",
a.a.mc);a.b("utils.toggleDomNodeCssClass",a.a.wa);a.b("utils.triggerEvent",a.a.ja);a.b("utils.unwrapObservable",a.a.c);a.b("utils.objectForEach",a.a.B);a.b("utils.addOrRemoveItem",a.a.$);a.b("unwrap",a.a.c);Function.prototype.bind||(Function.prototype.bind=function(a){var c=this,d=Array.prototype.slice.call(arguments);a=d.shift();return function(){return c.apply(a,d.concat(Array.prototype.slice.call(arguments)))}});a.a.f=new function(){function a(b,h){var g=b[d];if(!g||"null"===g||!e[g]){if(!h)return p;
g=b[d]="ko"+c++;e[g]={}}return e[g]}var c=0,d="__ko__"+(new Date).getTime(),e={};return{get:function(c,d){var e=a(c,!1);return e===p?p:e[d]},set:function(c,d,e){if(e!==p||a(c,!1)!==p)a(c,!0)[d]=e},clear:function(a){var b=a[d];return b?(delete e[b],a[d]=null,!0):!1},M:function(){return c++ +d}}};a.b("utils.domData",a.a.f);a.b("utils.domData.clear",a.a.f.clear);a.a.t=new function(){function b(b,c){var k=a.a.f.get(b,d);k===p&&c&&(k=[],a.a.f.set(b,d,k));return k}function c(d){var e=b(d,!1);if(e)for(var e=
e.slice(0),k=0;k<e.length;k++)e[k](d);a.a.f.clear(d);a.a.t.cleanExternalData(d);if(f[d.nodeType])for(e=d.firstChild;d=e;)e=d.nextSibling,8===d.nodeType&&c(d)}var d=a.a.f.M(),e={1:!0,8:!0,9:!0},f={1:!0,9:!0};return{Z:function(a,c){if("function"!=typeof c)throw Error("Callback must be a function");b(a,!0).push(c)},Eb:function(c,e){var k=b(c,!1);k&&(a.a.na(k,e),0==k.length&&a.a.f.set(c,d,p))},P:function(b){if(e[b.nodeType]&&(c(b),f[b.nodeType])){var d=[];a.a.ba(d,b.getElementsByTagName("*"));for(var k=
0,l=d.length;k<l;k++)c(d[k])}return b},removeNode:function(b){a.P(b);b.parentNode&&b.parentNode.removeChild(b)},cleanExternalData:function(a){t&&"function"==typeof t.cleanData&&t.cleanData([a])}}};a.P=a.a.t.P;a.removeNode=a.a.t.removeNode;a.b("cleanNode",a.P);a.b("removeNode",a.removeNode);a.b("utils.domNodeDisposal",a.a.t);a.b("utils.domNodeDisposal.addDisposeCallback",a.a.t.Z);a.b("utils.domNodeDisposal.removeDisposeCallback",a.a.t.Eb);(function(){a.a.ra=function(b){var c;if(t)if(t.parseHTML)c=
t.parseHTML(b)||[];else{if((c=t.clean([b]))&&c[0]){for(b=c[0];b.parentNode&&11!==b.parentNode.nodeType;)b=b.parentNode;b.parentNode&&b.parentNode.removeChild(b)}}else{var d=a.a.va(b).toLowerCase();c=w.createElement("div");d=d.match(/^<(thead|tbody|tfoot)/)&&[1,"<table>","</table>"]||!d.indexOf("<tr")&&[2,"<table><tbody>","</tbody></table>"]||(!d.indexOf("<td")||!d.indexOf("<th"))&&[3,"<table><tbody><tr>","</tr></tbody></table>"]||[0,"",""];b="ignored<div>"+d[1]+b+d[2]+"</div>";for("function"==typeof y.innerShiv?
c.appendChild(y.innerShiv(b)):c.innerHTML=b;d[0]--;)c=c.lastChild;c=a.a.Q(c.lastChild.childNodes)}return c};a.a.Xa=function(b,c){a.a.Ia(b);c=a.a.c(c);if(null!==c&&c!==p)if("string"!=typeof c&&(c=c.toString()),t)t(b).html(c);else for(var d=a.a.ra(c),e=0;e<d.length;e++)b.appendChild(d[e])}})();a.b("utils.parseHtmlFragment",a.a.ra);a.b("utils.setHtml",a.a.Xa);a.A=function(){function b(c,e){if(c)if(8==c.nodeType){var f=a.A.Bb(c.nodeValue);null!=f&&e.push({Vb:c,gc:f})}else if(1==c.nodeType)for(var f=0,
h=c.childNodes,g=h.length;f<g;f++)b(h[f],e)}var c={};return{Qa:function(a){if("function"!=typeof a)throw Error("You can only pass a function to ko.memoization.memoize()");var b=(4294967296*(1+Math.random())|0).toString(16).substring(1)+(4294967296*(1+Math.random())|0).toString(16).substring(1);c[b]=a;return"\x3c!--[ko_memo:"+b+"]--\x3e"},Lb:function(a,b){var f=c[a];if(f===p)throw Error("Couldn't find any memo with ID "+a+". Perhaps it's already been unmemoized.");try{return f.apply(null,b||[]),!0}finally{delete c[a]}},
Mb:function(c,e){var f=[];b(c,f);for(var h=0,g=f.length;h<g;h++){var k=f[h].Vb,l=[k];e&&a.a.ba(l,e);a.A.Lb(f[h].gc,l);k.nodeValue="";k.parentNode&&k.parentNode.removeChild(k)}},Bb:function(a){return(a=a.match(/^\[ko_memo\:(.*?)\]$/))?a[1]:null}}}();a.b("memoization",a.A);a.b("memoization.memoize",a.A.Qa);a.b("memoization.unmemoize",a.A.Lb);a.b("memoization.parseMemoText",a.A.Bb);a.b("memoization.unmemoizeDomNodeAndDescendants",a.A.Mb);a.Ja={throttle:function(b,c){b.throttleEvaluation=c;var d=null;
return a.h({read:b,write:function(a){clearTimeout(d);d=setTimeout(function(){b(a)},c)}})},rateLimit:function(a,c){var d,e,f;"number"==typeof c?d=c:(d=c.timeout,e=c.method);f="notifyWhenChangesStop"==e?Q:P;a.Pa(function(a){return f(a,d)})},notify:function(a,c){a.equalityComparer="always"==c?null:G}};var O={undefined:1,"boolean":1,number:1,string:1};a.b("extenders",a.Ja);a.Jb=function(b,c,d){this.target=b;this.Ca=c;this.Ub=d;this.vb=!1;a.u(this,"dispose",this.G)};a.Jb.prototype.G=function(){this.vb=
!0;this.Ub()};a.N=function(){a.a.ua(this,a.N.fn);this.I={}};var F="change",A={S:function(b,c,d){var e=this;d=d||F;var f=new a.Jb(e,c?b.bind(c):b,function(){a.a.na(e.I[d],f)});e.p&&e.p();e.I[d]||(e.I[d]=[]);e.I[d].push(f);return f},notifySubscribers:function(b,c){c=c||F;if(this.tb(c))try{a.l.kb();for(var d=this.I[c].slice(0),e=0,f;f=d[e];++e)f.vb||f.Ca(b)}finally{a.l.end()}},Pa:function(b){var c=this,d=a.w(c),e,f,h;c.ka||(c.ka=c.notifySubscribers,c.notifySubscribers=function(a,b){b&&b!==F?"beforeChange"===
b?c.eb(a):c.ka(a,b):c.fb(a)});var g=b(function(){d&&h===c&&(h=c());e=!1;c.Na(f,h)&&c.ka(f=h)});c.fb=function(a){e=!0;h=a;g()};c.eb=function(a){e||(f=a,c.ka(a,"beforeChange"))}},tb:function(a){return this.I[a]&&this.I[a].length},$b:function(){var b=0;a.a.B(this.I,function(a,d){b+=d.length});return b},Na:function(a,c){return!this.equalityComparer||!this.equalityComparer(a,c)},extend:function(b){var c=this;b&&a.a.B(b,function(b,e){var f=a.Ja[b];"function"==typeof f&&(c=f(c,e)||c)});return c}};a.u(A,
"subscribe",A.S);a.u(A,"extend",A.extend);a.u(A,"getSubscriptionsCount",A.$b);a.a.oa&&a.a.ta(A,Function.prototype);a.N.fn=A;a.xb=function(a){return null!=a&&"function"==typeof a.S&&"function"==typeof a.notifySubscribers};a.b("subscribable",a.N);a.b("isSubscribable",a.xb);a.ea=a.l=function(){function b(a){d.push(e);e=a}function c(){e=d.pop()}var d=[],e,f=0;return{kb:b,end:c,Db:function(b){if(e){if(!a.xb(b))throw Error("Only subscribable things can act as dependencies");e.Ca(b,b.Ob||(b.Ob=++f))}},v:function(a,
d,k){try{return b(),a.apply(d,k||[])}finally{c()}},ha:function(){if(e)return e.da.ha()},qa:function(){if(e)return e.qa}}}();a.b("computedContext",a.ea);a.b("computedContext.getDependenciesCount",a.ea.ha);a.b("computedContext.isInitial",a.ea.qa);a.n=function(b){function c(){if(0<arguments.length)return c.Na(d,arguments[0])&&(c.U(),d=arguments[0],c.T()),this;a.l.Db(c);return d}var d=b;a.N.call(c);a.a.ua(c,a.n.fn);c.p=function(){return d};c.T=function(){c.notifySubscribers(d)};c.U=function(){c.notifySubscribers(d,
"beforeChange")};a.u(c,"peek",c.p);a.u(c,"valueHasMutated",c.T);a.u(c,"valueWillMutate",c.U);return c};a.n.fn={equalityComparer:G};var E=a.n.lc="__ko_proto__";a.n.fn[E]=a.n;a.a.oa&&a.a.ta(a.n.fn,a.N.fn);a.Ka=function(b,c){return null===b||b===p||b[E]===p?!1:b[E]===c?!0:a.Ka(b[E],c)};a.w=function(b){return a.Ka(b,a.n)};a.yb=function(b){return"function"==typeof b&&b[E]===a.n||"function"==typeof b&&b[E]===a.h&&b.bc?!0:!1};a.b("observable",a.n);a.b("isObservable",a.w);a.b("isWriteableObservable",a.yb);
a.W=function(b){b=b||[];if("object"!=typeof b||!("length"in b))throw Error("The argument passed when initializing an observable array must be an array, or null, or undefined.");b=a.n(b);a.a.ua(b,a.W.fn);return b.extend({trackArrayChanges:!0})};a.W.fn={remove:function(b){for(var c=this.p(),d=[],e="function"!=typeof b||a.w(b)?function(a){return a===b}:b,f=0;f<c.length;f++){var h=c[f];e(h)&&(0===d.length&&this.U(),d.push(h),c.splice(f,1),f--)}d.length&&this.T();return d},removeAll:function(b){if(b===
p){var c=this.p(),d=c.slice(0);this.U();c.splice(0,c.length);this.T();return d}return b?this.remove(function(c){return 0<=a.a.m(b,c)}):[]},destroy:function(b){var c=this.p(),d="function"!=typeof b||a.w(b)?function(a){return a===b}:b;this.U();for(var e=c.length-1;0<=e;e--)d(c[e])&&(c[e]._destroy=!0);this.T()},destroyAll:function(b){return b===p?this.destroy(function(){return!0}):b?this.destroy(function(c){return 0<=a.a.m(b,c)}):[]},indexOf:function(b){var c=this();return a.a.m(c,b)},replace:function(a,
c){var d=this.indexOf(a);0<=d&&(this.U(),this.p()[d]=c,this.T())}};a.a.s("pop push reverse shift sort splice unshift".split(" "),function(b){a.W.fn[b]=function(){var a=this.p();this.U();this.lb(a,b,arguments);a=a[b].apply(a,arguments);this.T();return a}});a.a.s(["slice"],function(b){a.W.fn[b]=function(){var a=this();return a[b].apply(a,arguments)}});a.a.oa&&a.a.ta(a.W.fn,a.n.fn);a.b("observableArray",a.W);var I="arrayChange";a.Ja.trackArrayChanges=function(b){function c(){if(!d){d=!0;var c=b.notifySubscribers;
b.notifySubscribers=function(a,b){b&&b!==F||++f;return c.apply(this,arguments)};var k=[].concat(b.p()||[]);e=null;b.S(function(c){c=[].concat(c||[]);if(b.tb(I)){var d;if(!e||1<f)e=a.a.Da(k,c,{sparse:!0});d=e;d.length&&b.notifySubscribers(d,I)}k=c;e=null;f=0})}}if(!b.lb){var d=!1,e=null,f=0,h=b.S;b.S=b.subscribe=function(a,b,d){d===I&&c();return h.apply(this,arguments)};b.lb=function(b,c,l){function n(a,b,c){return h[h.length]={status:a,value:b,index:c}}if(d&&!f){var h=[],m=b.length,q=l.length,r=0;
switch(c){case "push":r=m;case "unshift":for(c=0;c<q;c++)n("added",l[c],r+c);break;case "pop":r=m-1;case "shift":m&&n("deleted",b[r],r);break;case "splice":c=Math.min(Math.max(0,0>l[0]?m+l[0]:l[0]),m);for(var m=1===q?m:Math.min(c+(l[1]||0),m),q=c+q-2,r=Math.max(m,q),B=[],u=[],D=2;c<r;++c,++D)c<m&&u.push(n("deleted",b[c],c)),c<q&&B.push(n("added",l[D],c));a.a.qb(u,B);break;default:return}e=h}}}};a.da=a.h=function(b,c,d){function e(){q=!0;a.a.B(v,function(a,b){b.G()});v={};x=0;n=!1}function f(){var a=
g.throttleEvaluation;a&&0<=a?(clearTimeout(t),t=setTimeout(h,a)):g.ya?g.ya():h()}function h(){if(!s&&!q){if(z&&z()){if(!m){p();return}}else m=!1;s=!0;try{var b=v,d=x;a.l.kb({Ca:function(a,c){q||(d&&b[c]?(v[c]=b[c],++x,delete b[c],--d):v[c]||(v[c]=a.S(f),++x))},da:g,qa:!x});v={};x=0;try{var e=c?r.call(c):r()}finally{a.l.end(),d&&a.a.B(b,function(a,b){b.G()}),n=!1}g.Na(l,e)&&(g.notifySubscribers(l,"beforeChange"),l=e,g.ya&&!g.throttleEvaluation||g.notifySubscribers(l))}finally{s=!1}x||p()}}function g(){if(0<
arguments.length){if("function"===typeof B)B.apply(c,arguments);else throw Error("Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.");return this}n&&h();a.l.Db(g);return l}function k(){return n||0<x}var l,n=!0,s=!1,m=!1,q=!1,r=b;r&&"object"==typeof r?(d=r,r=d.read):(d=d||{},r||(r=d.read));if("function"!=typeof r)throw Error("Pass a function that returns the value of the ko.computed");var B=d.write,u=d.disposeWhenNodeIsRemoved||
d.H||null,D=d.disposeWhen||d.Ga,z=D,p=e,v={},x=0,t=null;c||(c=d.owner);a.N.call(g);a.a.ua(g,a.h.fn);g.p=function(){n&&!x&&h();return l};g.ha=function(){return x};g.bc="function"===typeof d.write;g.G=function(){p()};g.ia=k;var w=g.Pa;g.Pa=function(a){w.call(g,a);g.ya=function(){g.eb(l);n=!0;g.fb(g)}};a.u(g,"peek",g.p);a.u(g,"dispose",g.G);a.u(g,"isActive",g.ia);a.u(g,"getDependenciesCount",g.ha);u&&(m=!0,u.nodeType&&(z=function(){return!a.a.Ha(u)||D&&D()}));!0!==d.deferEvaluation&&h();u&&k()&&u.nodeType&&
(p=function(){a.a.t.Eb(u,p);e()},a.a.t.Z(u,p));return g};a.dc=function(b){return a.Ka(b,a.h)};A=a.n.lc;a.h[A]=a.n;a.h.fn={equalityComparer:G};a.h.fn[A]=a.h;a.a.oa&&a.a.ta(a.h.fn,a.N.fn);a.b("dependentObservable",a.h);a.b("computed",a.h);a.b("isComputed",a.dc);(function(){function b(a,f,h){h=h||new d;a=f(a);if("object"!=typeof a||null===a||a===p||a instanceof Date||a instanceof String||a instanceof Number||a instanceof Boolean)return a;var g=a instanceof Array?[]:{};h.save(a,g);c(a,function(c){var d=
f(a[c]);switch(typeof d){case "boolean":case "number":case "string":case "function":g[c]=d;break;case "object":case "undefined":var n=h.get(d);g[c]=n!==p?n:b(d,f,h)}});return g}function c(a,b){if(a instanceof Array){for(var c=0;c<a.length;c++)b(c);"function"==typeof a.toJSON&&b("toJSON")}else for(c in a)b(c)}function d(){this.keys=[];this.cb=[]}a.Kb=function(c){if(0==arguments.length)throw Error("When calling ko.toJS, pass the object you want to convert.");return b(c,function(b){for(var c=0;a.w(b)&&
10>c;c++)b=b();return b})};a.toJSON=function(b,c,d){b=a.Kb(b);return a.a.$a(b,c,d)};d.prototype={save:function(b,c){var d=a.a.m(this.keys,b);0<=d?this.cb[d]=c:(this.keys.push(b),this.cb.push(c))},get:function(b){b=a.a.m(this.keys,b);return 0<=b?this.cb[b]:p}}})();a.b("toJS",a.Kb);a.b("toJSON",a.toJSON);(function(){a.i={q:function(b){switch(a.a.C(b)){case "option":return!0===b.__ko__hasDomDataOptionValue__?a.a.f.get(b,a.d.options.Sa):7>=a.a.pa?b.getAttributeNode("value")&&b.getAttributeNode("value").specified?
b.value:b.text:b.value;case "select":return 0<=b.selectedIndex?a.i.q(b.options[b.selectedIndex]):p;default:return b.value}},Y:function(b,c,d){switch(a.a.C(b)){case "option":switch(typeof c){case "string":a.a.f.set(b,a.d.options.Sa,p);"__ko__hasDomDataOptionValue__"in b&&delete b.__ko__hasDomDataOptionValue__;b.value=c;break;default:a.a.f.set(b,a.d.options.Sa,c),b.__ko__hasDomDataOptionValue__=!0,b.value="number"===typeof c?c:""}break;case "select":if(""===c||null===c)c=p;for(var e=-1,f=0,h=b.options.length,
g;f<h;++f)if(g=a.i.q(b.options[f]),g==c||""==g&&c===p){e=f;break}if(d||0<=e||c===p&&1<b.size)b.selectedIndex=e;break;default:if(null===c||c===p)c="";b.value=c}}}})();a.b("selectExtensions",a.i);a.b("selectExtensions.readValue",a.i.q);a.b("selectExtensions.writeValue",a.i.Y);a.g=function(){function b(b){b=a.a.va(b);123===b.charCodeAt(0)&&(b=b.slice(1,-1));var c=[],d=b.match(e),g,m,q=0;if(d){d.push(",");for(var r=0,B;B=d[r];++r){var u=B.charCodeAt(0);if(44===u){if(0>=q){g&&c.push(m?{key:g,value:m.join("")}:
{unknown:g});g=m=q=0;continue}}else if(58===u){if(!m)continue}else if(47===u&&r&&1<B.length)(u=d[r-1].match(f))&&!h[u[0]]&&(b=b.substr(b.indexOf(B)+1),d=b.match(e),d.push(","),r=-1,B="/");else if(40===u||123===u||91===u)++q;else if(41===u||125===u||93===u)--q;else if(!g&&!m){g=34===u||39===u?B.slice(1,-1):B;continue}m?m.push(B):m=[B]}}return c}var c=["true","false","null","undefined"],d=/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i,e=RegExp("\"(?:[^\"\\\\]|\\\\.)*\"|'(?:[^'\\\\]|\\\\.)*'|/(?:[^/\\\\]|\\\\.)*/w*|[^\\s:,/][^,\"'{}()/:[\\]]*[^\\s,\"'{}()/:[\\]]|[^\\s]",
"g"),f=/[\])"'A-Za-z0-9_$]+$/,h={"in":1,"return":1,"typeof":1},g={};return{ca:[],X:g,Ta:b,sa:function(k,l){function e(b,l){var k,r=a.getBindingHandler(b);if(r&&r.preprocess?l=r.preprocess(l,b,e):1){if(r=g[b])k=l,0<=a.a.m(c,k)?k=!1:(r=k.match(d),k=null===r?!1:r[1]?"Object("+r[1]+")"+r[2]:k),r=k;r&&h.push("'"+b+"':function(_z){"+k+"=_z}");q&&(l="function(){return "+l+" }");f.push("'"+b+"':"+l)}}l=l||{};var f=[],h=[],q=l.valueAccessors,r="string"===typeof k?b(k):k;a.a.s(r,function(a){e(a.key||a.unknown,
a.value)});h.length&&e("_ko_property_writers","{"+h.join(",")+" }");return f.join(",")},fc:function(a,b){for(var c=0;c<a.length;c++)if(a[c].key==b)return!0;return!1},xa:function(b,c,d,e,g){if(b&&a.w(b))!a.yb(b)||g&&b.p()===e||b(e);else if((b=c.get("_ko_property_writers"))&&b[d])b[d](e)}}}();a.b("expressionRewriting",a.g);a.b("expressionRewriting.bindingRewriteValidators",a.g.ca);a.b("expressionRewriting.parseObjectLiteral",a.g.Ta);a.b("expressionRewriting.preProcessBindings",a.g.sa);a.b("expressionRewriting._twoWayBindings",
a.g.X);a.b("jsonExpressionRewriting",a.g);a.b("jsonExpressionRewriting.insertPropertyAccessorsIntoJson",a.g.sa);(function(){function b(a){return 8==a.nodeType&&h.test(f?a.text:a.nodeValue)}function c(a){return 8==a.nodeType&&g.test(f?a.text:a.nodeValue)}function d(a,d){for(var e=a,k=1,g=[];e=e.nextSibling;){if(c(e)&&(k--,0===k))return g;g.push(e);b(e)&&k++}if(!d)throw Error("Cannot find closing comment tag to match: "+a.nodeValue);return null}function e(a,b){var c=d(a,b);return c?0<c.length?c[c.length-
1].nextSibling:a.nextSibling:null}var f=w&&"\x3c!--test--\x3e"===w.createComment("test").text,h=f?/^\x3c!--\s*ko(?:\s+([\s\S]+))?\s*--\x3e$/:/^\s*ko(?:\s+([\s\S]+))?\s*$/,g=f?/^\x3c!--\s*\/ko\s*--\x3e$/:/^\s*\/ko\s*$/,k={ul:!0,ol:!0};a.e={O:{},childNodes:function(a){return b(a)?d(a):a.childNodes},fa:function(c){if(b(c)){c=a.e.childNodes(c);for(var d=0,e=c.length;d<e;d++)a.removeNode(c[d])}else a.a.Ia(c)},R:function(c,d){if(b(c)){a.e.fa(c);for(var e=c.nextSibling,k=0,g=d.length;k<g;k++)e.parentNode.insertBefore(d[k],
e)}else a.a.R(c,d)},Cb:function(a,c){b(a)?a.parentNode.insertBefore(c,a.nextSibling):a.firstChild?a.insertBefore(c,a.firstChild):a.appendChild(c)},ub:function(c,d,e){e?b(c)?c.parentNode.insertBefore(d,e.nextSibling):e.nextSibling?c.insertBefore(d,e.nextSibling):c.appendChild(d):a.e.Cb(c,d)},firstChild:function(a){return b(a)?!a.nextSibling||c(a.nextSibling)?null:a.nextSibling:a.firstChild},nextSibling:function(a){b(a)&&(a=e(a));return a.nextSibling&&c(a.nextSibling)?null:a.nextSibling},ac:b,rc:function(a){return(a=
(f?a.text:a.nodeValue).match(h))?a[1]:null},Ab:function(d){if(k[a.a.C(d)]){var g=d.firstChild;if(g){do if(1===g.nodeType){var f;f=g.firstChild;var h=null;if(f){do if(h)h.push(f);else if(b(f)){var q=e(f,!0);q?f=q:h=[f]}else c(f)&&(h=[f]);while(f=f.nextSibling)}if(f=h)for(h=g.nextSibling,q=0;q<f.length;q++)h?d.insertBefore(f[q],h):d.appendChild(f[q])}while(g=g.nextSibling)}}}}})();a.b("virtualElements",a.e);a.b("virtualElements.allowedBindings",a.e.O);a.b("virtualElements.emptyNode",a.e.fa);a.b("virtualElements.insertAfter",
a.e.ub);a.b("virtualElements.prepend",a.e.Cb);a.b("virtualElements.setDomNodeChildren",a.e.R);(function(b){function c(c,e){var l=f.hasOwnProperty(c)?f[c]:b,n;l||(l=f[c]=new a.N,d(c,function(a){h[c]=a;delete f[c];n?l.notifySubscribers(a):setTimeout(function(){l.notifySubscribers(a)},0)}),n=!0);l.S(e)}function d(a,b){e("getConfig",[a],function(c){c?e("loadComponent",[a,c],function(a){b(a)}):b(null)})}function e(c,d,l,f){f||(f=a.j.loaders.slice(0));var h=f.shift();if(h){var m=h[c];if(m){var q=!1;if(m.apply(h,
d.concat(function(a){q?l(null):null!==a?l(a):e(c,d,l,f)}))!==b&&(q=!0,!h.suppressLoaderExceptions))throw Error("Component loaders must supply values by invoking the callback, not by returning values synchronously.");}else e(c,d,l,f)}else l(null)}var f={},h={};a.j={get:function(a,d){var e=h.hasOwnProperty(a)?h[a]:b;e?setTimeout(function(){d(e)},0):c(a,d)},mb:function(a){delete h[a]}};a.j.loaders=[];a.b("components",a.j);a.b("components.get",a.j.get);a.b("components.clearCachedDefinition",a.j.mb)})();
(function(){function b(a,b,e){function g(){0===--q&&e(h)}var h={},q=2,r=b.template;b=b.viewModel;r?f(a,r,function(b){c(a,b,function(a){h.template=a;g()})}):g();b?f(a,b,function(b){d(a,b,function(a){h.createViewModel=a;g()})}):g()}function c(b,c,d){if("string"===typeof c)b=a.a.ra(c),d(e(b,!1));else if(y.sc?c instanceof DocumentFragment:c&&11===c.nodeType)d(c);else if(c.element)if(c=c.element,y.tc?c instanceof HTMLElement:c&&c.tagName&&1===c.nodeType)d(e(c.childNodes,!0));else if("string"===typeof c){var g=
w.getElementById(c);g?d(e(g.childNodes,!0)):b("Cannot find element with ID "+c)}else b("Unknown element type: "+c);else b("Unknown template value: "+c)}function d(a,b,c){if("function"===typeof b)c(function(a,c){return new b(c)});else if("function"===typeof b[g])c(b[g]);else if("instance"in b){var e=b.instance;c(function(){return e})}else"viewModel"in b?d(a,b.viewModel,c):a("Unknown viewModel value: "+b)}function e(a,b){for(var c=w.createDocumentFragment(),d=0,e=a.length;d<e;d++)c.appendChild(b?a[d].cloneNode(!0):
a[d]);return c}function f(a,b,c){"string"===typeof b.require?M||y.require?(M||y.require)([b.require],c):a("Uses require, but no AMD loader is present"):c(b)}var h={};a.j.nc=function(b,c){if(!c)throw Error("Invalid configuration for "+b);if(a.j.wb(b))throw Error("Component "+b+" is already registered");h[b]=c};a.j.wb=function(a){return a in h};a.j.qc=function(b){delete h[b];a.j.mb(b)};a.j.ob={getConfig:function(a,b){b(h.hasOwnProperty(a)?h[a]:null)},loadComponent:function(a,c,d){function e(b){throw Error("Component '"+
a+"': "+b);}f(e,c,function(a){b(e,a,d)})}};var g="createViewModel";a.b("components.register",a.j.nc);a.b("components.isRegistered",a.j.wb);a.b("components.unregister",a.j.qc);a.b("components.defaultLoader",a.j.ob);a.j.loaders.push(a.j.ob)})();(function(){a.K=function(){this.Rb={}};a.a.extend(a.K.prototype,{nodeHasBindings:function(b){switch(b.nodeType){case 1:return null!=b.getAttribute("data-bind");case 8:return a.e.ac(b);default:return!1}},getBindings:function(a,c){var d=this.getBindingsString(a,
c);return d?this.parseBindingsString(d,c,a):null},getBindingAccessors:function(a,c){var d=this.getBindingsString(a,c);return d?this.parseBindingsString(d,c,a,{valueAccessors:!0}):null},getBindingsString:function(b){switch(b.nodeType){case 1:return b.getAttribute("data-bind");case 8:return a.e.rc(b);default:return null}},parseBindingsString:function(b,c,d,e){try{var f=this.Rb,h=b+(e&&e.valueAccessors||""),g;if(!(g=f[h])){var k,l="with($context){with($data||{}){return{"+a.g.sa(b,e)+"}}}";k=new Function("$context",
"$element",l);g=f[h]=k}return g(c,d)}catch(n){throw n.message="Unable to parse bindings.\nBindings value: "+b+"\nMessage: "+n.message,n;}}});a.K.instance=new a.K})();a.b("bindingProvider",a.K);(function(){function b(a){return function(){return a}}function c(a){return a()}function d(b){return a.a.Ra(a.l.v(b),function(a,c){return function(){return b()[c]}})}function e(a,b){return d(this.getBindings.bind(this,a,b))}function f(b,c,d){var e,g=a.e.firstChild(c),f=a.K.instance,k=f.preprocessNode;if(k){for(;e=
g;)g=a.e.nextSibling(e),k.call(f,e);g=a.e.firstChild(c)}for(;e=g;)g=a.e.nextSibling(e),h(b,e,d)}function h(b,c,d){var e=!0,g=1===c.nodeType;g&&a.e.Ab(c);if(g&&d||a.K.instance.nodeHasBindings(c))e=k(c,null,b,d).shouldBindDescendants;e&&!n[a.a.C(c)]&&f(b,c,!g)}function g(b){var c=[],d={},e=[];a.a.B(b,function z(g){if(!d[g]){var f=a.getBindingHandler(g);f&&(f.after&&(e.push(g),a.a.s(f.after,function(c){if(b[c]){if(-1!==a.a.m(e,c))throw Error("Cannot combine the following bindings, because they have a cyclic dependency: "+
e.join(", "));z(c)}}),e.length--),c.push({key:g,sb:f}));d[g]=!0}});return c}function k(b,d,f,k){var h=a.a.f.get(b,s);if(!d){if(h)throw Error("You cannot apply bindings multiple times to the same element.");a.a.f.set(b,s,!0)}!h&&k&&a.Ib(b,f);var l;if(d&&"function"!==typeof d)l=d;else{var n=a.K.instance,m=n.getBindingAccessors||e,x=a.h(function(){(l=d?d(f,b):m.call(n,b,f))&&f.F&&f.F();return l},null,{H:b});l&&x.ia()||(x=null)}var t;if(l){var w=x?function(a){return function(){return c(x()[a])}}:function(a){return l[a]},
y=function(){return a.a.Ra(x?x():l,c)};y.get=function(a){return l[a]&&c(w(a))};y.has=function(a){return a in l};k=g(l);a.a.s(k,function(c){var d=c.sb.init,e=c.sb.update,g=c.key;if(8===b.nodeType&&!a.e.O[g])throw Error("The binding '"+g+"' cannot be used with virtual elements");try{"function"==typeof d&&a.l.v(function(){var a=d(b,w(g),y,f.$data,f);if(a&&a.controlsDescendantBindings){if(t!==p)throw Error("Multiple bindings ("+t+" and "+g+") are trying to control descendant bindings of the same element. You cannot use these bindings together on the same element.");
t=g}}),"function"==typeof e&&a.h(function(){e(b,w(g),y,f.$data,f)},null,{H:b})}catch(k){throw k.message='Unable to process binding "'+g+": "+l[g]+'"\nMessage: '+k.message,k;}})}return{shouldBindDescendants:t===p}}function l(b){return b&&b instanceof a.J?b:new a.J(b)}a.d={};var n={script:!0};a.getBindingHandler=function(b){return a.d[b]};a.J=function(b,c,d,e){var g=this,f="function"==typeof b&&!a.w(b),k,l=a.h(function(){var k=f?b():b,h=a.a.c(k);c?(c.F&&c.F(),a.a.extend(g,c),l&&(g.F=l)):(g.$parents=
[],g.$root=h,g.ko=a);g.$rawData=k;g.$data=h;d&&(g[d]=h);e&&e(g,c,h);return g.$data},null,{Ga:function(){return k&&!a.a.gb(k)},H:!0});l.ia()&&(g.F=l,l.equalityComparer=null,k=[],l.Nb=function(b){k.push(b);a.a.t.Z(b,function(b){a.a.na(k,b);k.length||(l.G(),g.F=l=p)})})};a.J.prototype.createChildContext=function(b,c,d){return new a.J(b,this,c,function(a,b){a.$parentContext=b;a.$parent=b.$data;a.$parents=(b.$parents||[]).slice(0);a.$parents.unshift(a.$parent);d&&d(a)})};a.J.prototype.extend=function(b){return new a.J(this.F||
this.$data,this,null,function(c,d){c.$rawData=d.$rawData;a.a.extend(c,"function"==typeof b?b():b)})};var s=a.a.f.M(),m=a.a.f.M();a.Ib=function(b,c){if(2==arguments.length)a.a.f.set(b,m,c),c.F&&c.F.Nb(b);else return a.a.f.get(b,m)};a.za=function(b,c,d){1===b.nodeType&&a.e.Ab(b);return k(b,c,l(d),!0)};a.Pb=function(c,e,g){g=l(g);return a.za(c,"function"===typeof e?d(e.bind(null,g,c)):a.a.Ra(e,b),g)};a.Aa=function(a,b){1!==b.nodeType&&8!==b.nodeType||f(l(a),b,!0)};a.hb=function(a,b){!t&&y.jQuery&&(t=
y.jQuery);if(b&&1!==b.nodeType&&8!==b.nodeType)throw Error("ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node");b=b||y.document.body;h(l(a),b,!0)};a.Fa=function(b){switch(b.nodeType){case 1:case 8:var c=a.Ib(b);if(c)return c;if(b.parentNode)return a.Fa(b.parentNode)}return p};a.Tb=function(b){return(b=a.Fa(b))?b.$data:p};a.b("bindingHandlers",a.d);a.b("applyBindings",a.hb);a.b("applyBindingsToDescendants",a.Aa);a.b("applyBindingAccessorsToNode",a.za);
a.b("applyBindingsToNode",a.Pb);a.b("contextFor",a.Fa);a.b("dataFor",a.Tb)})();(function(){function b(b){var d=(b=a.a.f.get(b,c))&&b.dispose;"function"===typeof d&&d.call(b)}var c="_ko_componentvm_"+(new Date).valueOf(),d="_ko_componentload_"+(new Date).valueOf(),e=0;a.d.component={init:function(c){a.a.t.Z(c,b);return{controlsDescendantBindings:!0}},update:function(f,h,g,k,l){h=h();var n=a.a.c(h.name),s=a.a.c(h.params);if(!n)throw Error("No component name specified");var m=f[d]=++e;a.j.get(n,function(e){if(f[d]===
m){delete f[d];b(f);if(!e)throw Error("Unknown component '"+n+"'");var g=e.template;if(!g)throw Error("Component '"+n+"' has no template");g=a.a.Q(g.cloneNode(!0).childNodes);a.e.R(f,g);e=(e=e.createViewModel)?e({element:f},s):s;g=l.createChildContext(e);a.a.f.set(f,c,e);a.Aa(g,f)}})}};a.e.O.component=!0})();var N={"class":"className","for":"htmlFor"};a.d.attr={update:function(b,c){var d=a.a.c(c())||{};a.a.B(d,function(c,d){d=a.a.c(d);var h=!1===d||null===d||d===p;h&&b.removeAttribute(c);8>=a.a.pa&&
c in N?(c=N[c],h?b.removeAttribute(c):b[c]=d):h||b.setAttribute(c,d.toString());"name"===c&&a.a.Gb(b,h?"":d.toString())})}};(function(){a.d.checked={after:["value","attr"],init:function(b,c,d){function e(){return d.has("checkedValue")?a.a.c(d.get("checkedValue")):b.value}function f(){var g=b.checked,f=s?e():g;if(!a.ea.qa()&&(!k||g)){var h=a.l.v(c);l?n!==f?(g&&(a.a.$(h,f,!0),a.a.$(h,n,!1)),n=f):a.a.$(h,f,g):a.g.xa(h,d,"checked",f,!0)}}function h(){var d=a.a.c(c());b.checked=l?0<=a.a.m(d,e()):g?d:e()===
d}var g="checkbox"==b.type,k="radio"==b.type;if(g||k){var l=g&&a.a.c(c())instanceof Array,n=l?e():p,s=k||l;k&&!b.name&&a.d.uniqueName.init(b,function(){return!0});a.da(f,null,{H:b});a.a.r(b,"click",f);a.da(h,null,{H:b})}}};a.g.X.checked=!0;a.d.checkedValue={update:function(b,c){b.value=a.a.c(c())}}})();a.d.css={update:function(b,c){var d=a.a.c(c());"object"==typeof d?a.a.B(d,function(c,d){d=a.a.c(d);a.a.wa(b,c,d)}):(d=String(d||""),a.a.wa(b,b.__ko__cssValue,!1),b.__ko__cssValue=d,a.a.wa(b,d,!0))}};
a.d.enable={update:function(b,c){var d=a.a.c(c());d&&b.disabled?b.removeAttribute("disabled"):d||b.disabled||(b.disabled=!0)}};a.d.disable={update:function(b,c){a.d.enable.update(b,function(){return!a.a.c(c())})}};a.d.event={init:function(b,c,d,e,f){var h=c()||{};a.a.B(h,function(g){"string"==typeof g&&a.a.r(b,g,function(b){var l,h=c()[g];if(h){try{var s=a.a.Q(arguments);e=f.$data;s.unshift(e);l=h.apply(e,s)}finally{!0!==l&&(b.preventDefault?b.preventDefault():b.returnValue=!1)}!1===d.get(g+"Bubble")&&
(b.cancelBubble=!0,b.stopPropagation&&b.stopPropagation())}})})}};a.d.foreach={zb:function(b){return function(){var c=b(),d=a.a.Ua(c);if(!d||"number"==typeof d.length)return{foreach:c,templateEngine:a.L.Ma};a.a.c(c);return{foreach:d.data,as:d.as,includeDestroyed:d.includeDestroyed,afterAdd:d.afterAdd,beforeRemove:d.beforeRemove,afterRender:d.afterRender,beforeMove:d.beforeMove,afterMove:d.afterMove,templateEngine:a.L.Ma}}},init:function(b,c){return a.d.template.init(b,a.d.foreach.zb(c))},update:function(b,
c,d,e,f){return a.d.template.update(b,a.d.foreach.zb(c),d,e,f)}};a.g.ca.foreach=!1;a.e.O.foreach=!0;a.d.hasfocus={init:function(b,c,d){function e(e){b.__ko_hasfocusUpdating=!0;var k=b.ownerDocument;if("activeElement"in k){var f;try{f=k.activeElement}catch(h){f=k.body}e=f===b}k=c();a.g.xa(k,d,"hasfocus",e,!0);b.__ko_hasfocusLastValue=e;b.__ko_hasfocusUpdating=!1}var f=e.bind(null,!0),h=e.bind(null,!1);a.a.r(b,"focus",f);a.a.r(b,"focusin",f);a.a.r(b,"blur",h);a.a.r(b,"focusout",h)},update:function(b,
c){var d=!!a.a.c(c());b.__ko_hasfocusUpdating||b.__ko_hasfocusLastValue===d||(d?b.focus():b.blur(),a.l.v(a.a.ja,null,[b,d?"focusin":"focusout"]))}};a.g.X.hasfocus=!0;a.d.hasFocus=a.d.hasfocus;a.g.X.hasFocus=!0;a.d.html={init:function(){return{controlsDescendantBindings:!0}},update:function(b,c){a.a.Xa(b,c())}};H("if");H("ifnot",!1,!0);H("with",!0,!1,function(a,c){return a.createChildContext(c)});var J={};a.d.options={init:function(b){if("select"!==a.a.C(b))throw Error("options binding applies only to SELECT elements");
for(;0<b.length;)b.remove(0);return{controlsDescendantBindings:!0}},update:function(b,c,d){function e(){return a.a.ma(b.options,function(a){return a.selected})}function f(a,b,c){var d=typeof b;return"function"==d?b(a):"string"==d?a[b]:c}function h(c,d){if(s.length){var e=0<=a.a.m(s,a.i.q(d[0]));a.a.Hb(d[0],e);m&&!e&&a.l.v(a.a.ja,null,[b,"change"])}}var g=0!=b.length&&b.multiple?b.scrollTop:null,k=a.a.c(c()),l=d.get("optionsIncludeDestroyed");c={};var n,s;s=b.multiple?a.a.Ba(e(),a.i.q):0<=b.selectedIndex?
[a.i.q(b.options[b.selectedIndex])]:[];k&&("undefined"==typeof k.length&&(k=[k]),n=a.a.ma(k,function(b){return l||b===p||null===b||!a.a.c(b._destroy)}),d.has("optionsCaption")&&(k=a.a.c(d.get("optionsCaption")),null!==k&&k!==p&&n.unshift(J)));var m=!1;c.beforeRemove=function(a){b.removeChild(a)};k=h;d.has("optionsAfterRender")&&(k=function(b,c){h(0,c);a.l.v(d.get("optionsAfterRender"),null,[c[0],b!==J?b:p])});a.a.Wa(b,n,function(c,e,g){g.length&&(s=g[0].selected?[a.i.q(g[0])]:[],m=!0);e=b.ownerDocument.createElement("option");
c===J?(a.a.Za(e,d.get("optionsCaption")),a.i.Y(e,p)):(g=f(c,d.get("optionsValue"),c),a.i.Y(e,a.a.c(g)),c=f(c,d.get("optionsText"),g),a.a.Za(e,c));return[e]},c,k);a.l.v(function(){d.get("valueAllowUnset")&&d.has("value")?a.i.Y(b,a.a.c(d.get("value")),!0):(b.multiple?s.length&&e().length<s.length:s.length&&0<=b.selectedIndex?a.i.q(b.options[b.selectedIndex])!==s[0]:s.length||0<=b.selectedIndex)&&a.a.ja(b,"change")});a.a.Xb(b);g&&20<Math.abs(g-b.scrollTop)&&(b.scrollTop=g)}};a.d.options.Sa=a.a.f.M();
a.d.selectedOptions={after:["options","foreach"],init:function(b,c,d){a.a.r(b,"change",function(){var e=c(),f=[];a.a.s(b.getElementsByTagName("option"),function(b){b.selected&&f.push(a.i.q(b))});a.g.xa(e,d,"selectedOptions",f)})},update:function(b,c){if("select"!=a.a.C(b))throw Error("values binding applies only to SELECT elements");var d=a.a.c(c());d&&"number"==typeof d.length&&a.a.s(b.getElementsByTagName("option"),function(b){var c=0<=a.a.m(d,a.i.q(b));a.a.Hb(b,c)})}};a.g.X.selectedOptions=!0;
a.d.style={update:function(b,c){var d=a.a.c(c()||{});a.a.B(d,function(c,d){d=a.a.c(d);b.style[c]=d||""})}};a.d.submit={init:function(b,c,d,e,f){if("function"!=typeof c())throw Error("The value for a submit binding must be a function");a.a.r(b,"submit",function(a){var d,e=c();try{d=e.call(f.$data,b)}finally{!0!==d&&(a.preventDefault?a.preventDefault():a.returnValue=!1)}})}};a.d.text={init:function(){return{controlsDescendantBindings:!0}},update:function(b,c){a.a.Za(b,c())}};a.e.O.text=!0;a.d.uniqueName=
{init:function(b,c){if(c()){var d="ko_unique_"+ ++a.d.uniqueName.Sb;a.a.Gb(b,d)}}};a.d.uniqueName.Sb=0;a.d.value={after:["options","foreach"],init:function(b,c,d){function e(){g=!1;var e=c(),f=a.i.q(b);a.g.xa(e,d,"value",f)}var f=["change"],h=d.get("valueUpdate"),g=!1;h&&("string"==typeof h&&(h=[h]),a.a.ba(f,h),f=a.a.jb(f));!a.a.pa||"input"!=b.tagName.toLowerCase()||"text"!=b.type||"off"==b.autocomplete||b.form&&"off"==b.form.autocomplete||-1!=a.a.m(f,"propertychange")||(a.a.r(b,"propertychange",
function(){g=!0}),a.a.r(b,"focus",function(){g=!1}),a.a.r(b,"blur",function(){g&&e()}));a.a.s(f,function(c){var d=e;a.a.pc(c,"after")&&(d=function(){setTimeout(e,0)},c=c.substring(5));a.a.r(b,c,d)})},update:function(b,c,d){var e=a.a.c(c());c=a.i.q(b);if(e!==c)if("select"===a.a.C(b)){var f=d.get("valueAllowUnset");d=function(){a.i.Y(b,e,f)};d();f||e===a.i.q(b)?setTimeout(d,0):a.l.v(a.a.ja,null,[b,"change"])}else a.i.Y(b,e)}};a.g.X.value=!0;a.d.visible={update:function(b,c){var d=a.a.c(c()),e="none"!=
b.style.display;d&&!e?b.style.display="":!d&&e&&(b.style.display="none")}};(function(b){a.d[b]={init:function(c,d,e,f,h){return a.d.event.init.call(this,c,function(){var a={};a[b]=d();return a},e,f,h)}}})("click");a.D=function(){};a.D.prototype.renderTemplateSource=function(){throw Error("Override renderTemplateSource");};a.D.prototype.createJavaScriptEvaluatorBlock=function(){throw Error("Override createJavaScriptEvaluatorBlock");};a.D.prototype.makeTemplateSource=function(b,c){if("string"==typeof b){c=
c||w;var d=c.getElementById(b);if(!d)throw Error("Cannot find template with ID "+b);return new a.o.k(d)}if(1==b.nodeType||8==b.nodeType)return new a.o.aa(b);throw Error("Unknown template type: "+b);};a.D.prototype.renderTemplate=function(a,c,d,e){a=this.makeTemplateSource(a,e);return this.renderTemplateSource(a,c,d)};a.D.prototype.isTemplateRewritten=function(a,c){return!1===this.allowTemplateRewriting?!0:this.makeTemplateSource(a,c).data("isRewritten")};a.D.prototype.rewriteTemplate=function(a,c,
d){a=this.makeTemplateSource(a,d);c=c(a.text());a.text(c);a.data("isRewritten",!0)};a.b("templateEngine",a.D);a.ab=function(){function b(b,c,d,g){b=a.g.Ta(b);for(var k=a.g.ca,l=0;l<b.length;l++){var n=b[l].key;if(k.hasOwnProperty(n)){var s=k[n];if("function"===typeof s){if(n=s(b[l].value))throw Error(n);}else if(!s)throw Error("This template engine does not support the '"+n+"' binding within its templates");}}d="ko.__tr_ambtns(function($context,$element){return(function(){return{ "+a.g.sa(b,{valueAccessors:!0})+
" } })()},'"+d.toLowerCase()+"')";return g.createJavaScriptEvaluatorBlock(d)+c}var c=/(<([a-z]+\d*)(?:\s+(?!data-bind\s*=\s*)[a-z0-9\-]+(?:=(?:\"[^\"]*\"|\'[^\']*\'))?)*\s+)data-bind\s*=\s*(["'])([\s\S]*?)\3/gi,d=/\x3c!--\s*ko\b\s*([\s\S]*?)\s*--\x3e/g;return{Yb:function(b,c,d){c.isTemplateRewritten(b,d)||c.rewriteTemplate(b,function(b){return a.ab.hc(b,c)},d)},hc:function(a,f){return a.replace(c,function(a,c,d,e,n){return b(n,c,d,f)}).replace(d,function(a,c){return b(c,"\x3c!-- ko --\x3e","#comment",
f)})},Qb:function(b,c){return a.A.Qa(function(d,g){var k=d.nextSibling;k&&k.nodeName.toLowerCase()===c&&a.za(k,b,g)})}}}();a.b("__tr_ambtns",a.ab.Qb);(function(){a.o={};a.o.k=function(a){this.k=a};a.o.k.prototype.text=function(){var b=a.a.C(this.k),b="script"===b?"text":"textarea"===b?"value":"innerHTML";if(0==arguments.length)return this.k[b];var c=arguments[0];"innerHTML"===b?a.a.Xa(this.k,c):this.k[b]=c};var b=a.a.f.M()+"_";a.o.k.prototype.data=function(c){if(1===arguments.length)return a.a.f.get(this.k,
b+c);a.a.f.set(this.k,b+c,arguments[1])};var c=a.a.f.M();a.o.aa=function(a){this.k=a};a.o.aa.prototype=new a.o.k;a.o.aa.prototype.text=function(){if(0==arguments.length){var b=a.a.f.get(this.k,c)||{};b.bb===p&&b.Ea&&(b.bb=b.Ea.innerHTML);return b.bb}a.a.f.set(this.k,c,{bb:arguments[0]})};a.o.k.prototype.nodes=function(){if(0==arguments.length)return(a.a.f.get(this.k,c)||{}).Ea;a.a.f.set(this.k,c,{Ea:arguments[0]})};a.b("templateSources",a.o);a.b("templateSources.domElement",a.o.k);a.b("templateSources.anonymousTemplate",
a.o.aa)})();(function(){function b(b,c,d){var e;for(c=a.e.nextSibling(c);b&&(e=b)!==c;)b=a.e.nextSibling(e),d(e,b)}function c(c,d){if(c.length){var e=c[0],f=c[c.length-1],h=e.parentNode,m=a.K.instance,q=m.preprocessNode;if(q){b(e,f,function(a,b){var c=a.previousSibling,d=q.call(m,a);d&&(a===e&&(e=d[0]||b),a===f&&(f=d[d.length-1]||c))});c.length=0;if(!e)return;e===f?c.push(e):(c.push(e,f),a.a.ga(c,h))}b(e,f,function(b){1!==b.nodeType&&8!==b.nodeType||a.hb(d,b)});b(e,f,function(b){1!==b.nodeType&&8!==
b.nodeType||a.A.Mb(b,[d])});a.a.ga(c,h)}}function d(a){return a.nodeType?a:0<a.length?a[0]:null}function e(b,e,h,n,s){s=s||{};var m=b&&d(b),m=m&&m.ownerDocument,q=s.templateEngine||f;a.ab.Yb(h,q,m);h=q.renderTemplate(h,n,s,m);if("number"!=typeof h.length||0<h.length&&"number"!=typeof h[0].nodeType)throw Error("Template engine must return an array of DOM nodes");m=!1;switch(e){case "replaceChildren":a.e.R(b,h);m=!0;break;case "replaceNode":a.a.Fb(b,h);m=!0;break;case "ignoreTargetNode":break;default:throw Error("Unknown renderMode: "+
e);}m&&(c(h,n),s.afterRender&&a.l.v(s.afterRender,null,[h,n.$data]));return h}var f;a.Ya=function(b){if(b!=p&&!(b instanceof a.D))throw Error("templateEngine must inherit from ko.templateEngine");f=b};a.Va=function(b,c,h,n,s){h=h||{};if((h.templateEngine||f)==p)throw Error("Set a template engine before calling renderTemplate");s=s||"replaceChildren";if(n){var m=d(n);return a.h(function(){var f=c&&c instanceof a.J?c:new a.J(a.a.c(c)),p=a.w(b)?b():"function"==typeof b?b(f.$data,f):b,f=e(n,s,p,f,h);
"replaceNode"==s&&(n=f,m=d(n))},null,{Ga:function(){return!m||!a.a.Ha(m)},H:m&&"replaceNode"==s?m.parentNode:m})}return a.A.Qa(function(d){a.Va(b,c,h,d,"replaceNode")})};a.oc=function(b,d,f,h,s){function m(a,b){c(b,r);f.afterRender&&f.afterRender(b,a)}function q(a,c){r=s.createChildContext(a,f.as,function(a){a.$index=c});var d="function"==typeof b?b(a,r):b;return e(null,"ignoreTargetNode",d,r,f)}var r;return a.h(function(){var b=a.a.c(d)||[];"undefined"==typeof b.length&&(b=[b]);b=a.a.ma(b,function(b){return f.includeDestroyed||
b===p||null===b||!a.a.c(b._destroy)});a.l.v(a.a.Wa,null,[h,b,q,f,m])},null,{H:h})};var h=a.a.f.M();a.d.template={init:function(b,c){var d=a.a.c(c());"string"==typeof d||d.name?a.e.fa(b):(d=a.e.childNodes(b),d=a.a.ic(d),(new a.o.aa(b)).nodes(d));return{controlsDescendantBindings:!0}},update:function(b,c,d,e,f){var m=c(),q;c=a.a.c(m);d=!0;e=null;"string"==typeof c?c={}:(m=c.name,"if"in c&&(d=a.a.c(c["if"])),d&&"ifnot"in c&&(d=!a.a.c(c.ifnot)),q=a.a.c(c.data));"foreach"in c?e=a.oc(m||b,d&&c.foreach||
[],c,b,f):d?(f="data"in c?f.createChildContext(q,c.as):f,e=a.Va(m||b,f,c,b)):a.e.fa(b);f=e;(q=a.a.f.get(b,h))&&"function"==typeof q.G&&q.G();a.a.f.set(b,h,f&&f.ia()?f:p)}};a.g.ca.template=function(b){b=a.g.Ta(b);return 1==b.length&&b[0].unknown||a.g.fc(b,"name")?null:"This template engine does not support anonymous templates nested within its templates"};a.e.O.template=!0})();a.b("setTemplateEngine",a.Ya);a.b("renderTemplate",a.Va);a.a.qb=function(a,c,d){if(a.length&&c.length){var e,f,h,g,k;for(e=
f=0;(!d||e<d)&&(g=a[f]);++f){for(h=0;k=c[h];++h)if(g.value===k.value){g.moved=k.index;k.moved=g.index;c.splice(h,1);e=h=0;break}e+=h}}};a.a.Da=function(){function b(b,d,e,f,h){var g=Math.min,k=Math.max,l=[],n,p=b.length,m,q=d.length,r=q-p||1,t=p+q+1,u,w,z;for(n=0;n<=p;n++)for(w=u,l.push(u=[]),z=g(q,n+r),m=k(0,n-1);m<=z;m++)u[m]=m?n?b[n-1]===d[m-1]?w[m-1]:g(w[m]||t,u[m-1]||t)+1:m+1:n+1;g=[];k=[];r=[];n=p;for(m=q;n||m;)q=l[n][m]-1,m&&q===l[n][m-1]?k.push(g[g.length]={status:e,value:d[--m],index:m}):
n&&q===l[n-1][m]?r.push(g[g.length]={status:f,value:b[--n],index:n}):(--m,--n,h.sparse||g.push({status:"retained",value:d[m]}));a.a.qb(k,r,10*p);return g.reverse()}return function(a,d,e){e="boolean"===typeof e?{dontLimitMoves:e}:e||{};a=a||[];d=d||[];return a.length<=d.length?b(a,d,"added","deleted",e):b(d,a,"deleted","added",e)}}();a.b("utils.compareArrays",a.a.Da);(function(){function b(b,c,f,h,g){var k=[],l=a.h(function(){var l=c(f,g,a.a.ga(k,b))||[];0<k.length&&(a.a.Fb(k,l),h&&a.l.v(h,null,[f,
l,g]));k.length=0;a.a.ba(k,l)},null,{H:b,Ga:function(){return!a.a.gb(k)}});return{V:k,h:l.ia()?l:p}}var c=a.a.f.M();a.a.Wa=function(d,e,f,h,g){function k(b,c){v=s[c];u!==c&&(y[b]=v);v.La(u++);a.a.ga(v.V,d);r.push(v);z.push(v)}function l(b,c){if(b)for(var d=0,e=c.length;d<e;d++)c[d]&&a.a.s(c[d].V,function(a){b(a,d,c[d].la)})}e=e||[];h=h||{};var n=a.a.f.get(d,c)===p,s=a.a.f.get(d,c)||[],m=a.a.Ba(s,function(a){return a.la}),q=a.a.Da(m,e,h.dontLimitMoves),r=[],t=0,u=0,w=[],z=[];e=[];for(var y=[],m=[],
v,x=0,A,C;A=q[x];x++)switch(C=A.moved,A.status){case "deleted":C===p&&(v=s[t],v.h&&v.h.G(),w.push.apply(w,a.a.ga(v.V,d)),h.beforeRemove&&(e[x]=v,z.push(v)));t++;break;case "retained":k(x,t++);break;case "added":C!==p?k(x,C):(v={la:A.value,La:a.n(u++)},r.push(v),z.push(v),n||(m[x]=v))}l(h.beforeMove,y);a.a.s(w,h.beforeRemove?a.P:a.removeNode);for(var x=0,n=a.e.firstChild(d),E;v=z[x];x++){v.V||a.a.extend(v,b(d,f,v.la,g,v.La));for(t=0;q=v.V[t];n=q.nextSibling,E=q,t++)q!==n&&a.e.ub(d,q,E);!v.cc&&g&&(g(v.la,
v.V,v.La),v.cc=!0)}l(h.beforeRemove,e);l(h.afterMove,y);l(h.afterAdd,m);a.a.f.set(d,c,r)}})();a.b("utils.setDomNodeChildrenFromArrayMapping",a.a.Wa);a.L=function(){this.allowTemplateRewriting=!1};a.L.prototype=new a.D;a.L.prototype.renderTemplateSource=function(b){var c=(9>a.a.pa?0:b.nodes)?b.nodes():null;if(c)return a.a.Q(c.cloneNode(!0).childNodes);b=b.text();return a.a.ra(b)};a.L.Ma=new a.L;a.Ya(a.L.Ma);a.b("nativeTemplateEngine",a.L);(function(){a.Oa=function(){var a=this.ec=function(){if(!t||
!t.tmpl)return 0;try{if(0<=t.tmpl.tag.tmpl.open.toString().indexOf("__"))return 2}catch(a){}return 1}();this.renderTemplateSource=function(b,e,f){f=f||{};if(2>a)throw Error("Your version of jQuery.tmpl is too old. Please upgrade to jQuery.tmpl 1.0.0pre or later.");var h=b.data("precompiled");h||(h=b.text()||"",h=t.template(null,"{{ko_with $item.koBindingContext}}"+h+"{{/ko_with}}"),b.data("precompiled",h));b=[e.$data];e=t.extend({koBindingContext:e},f.templateOptions);e=t.tmpl(h,b,e);e.appendTo(w.createElement("div"));
t.fragments={};return e};this.createJavaScriptEvaluatorBlock=function(a){return"{{ko_code ((function() { return "+a+" })()) }}"};this.addTemplate=function(a,b){w.write("<script type='text/html' id='"+a+"'>"+b+"\x3c/script>")};0<a&&(t.tmpl.tag.ko_code={open:"__.push($1 || '');"},t.tmpl.tag.ko_with={open:"with($1) {",close:"} "})};a.Oa.prototype=new a.D;var b=new a.Oa;0<b.ec&&a.Ya(b);a.b("jqueryTmplTemplateEngine",a.Oa)})()})})();})();
